/**
 * Zill data model (Drizzle ORM · SQLite / libSQL / Turso).
 *
 * Conventions
 *  - ids: text, generated by `createId()`
 *  - instants: integer unix milliseconds (`timestamp_ms`) — always UTC
 *  - local wall-clock values: text 'YYYY-MM-DD' / 'HH:mm', interpreted in the branch's IANA time zone
 *  - money: integer minor units (halalas)
 *  - localized text: JSON `{ ar, en, … }` so new locales need no migration
 */
import { sql } from 'drizzle-orm';
import { index, integer, primaryKey, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';
import type { LocalizedText } from '../i18n/localized';

const ts = (name: string) => integer(name, { mode: 'timestamp_ms' });
const createdAt = () => ts('created_at').notNull().default(sql`(unixepoch() * 1000)`);
const updatedAt = () => ts('updated_at').notNull().default(sql`(unixepoch() * 1000)`);
const localized = (name: string) => text(name, { mode: 'json' }).$type<LocalizedText>();
const json = <T>(name: string) => text(name, { mode: 'json' }).$type<T>();
const bool = (name: string) => integer(name, { mode: 'boolean' });

// ————————————————————————————————————————————— auth (Better Auth) —————————————————————————————————————————————

export const ROLES = ['owner', 'manager', 'host', 'kitchen', 'waiter', 'editor', 'customer'] as const;
export type Role = (typeof ROLES)[number];

export interface DietaryProfile {
  diets: string[]; // 'vegetarian' | 'vegan' | 'gluten-free' | 'dairy-free' …
  avoidAllergens: string[]; // allergen codes
  maxSpice?: number;
}

export const users = sqliteTable(
  'users',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: bool('email_verified').notNull().default(false),
    image: text('image'),
    role: text('role').$type<Role>().notNull().default('customer'),
    phone: text('phone'),
    locale: text('locale').notNull().default('ar'),
    branchId: text('branch_id'),
    dietary: json<DietaryProfile>('dietary'),
    marketingEmail: bool('marketing_email').notNull().default(false),
    marketingSms: bool('marketing_sms').notNull().default(false),
    loyaltyPoints: integer('loyalty_points').notNull().default(0),
    lifetimePoints: integer('lifetime_points').notNull().default(0),
    tags: json<string[]>('tags'),
    staffNotes: text('staff_notes'),
    disabled: bool('disabled').notNull().default(false),
    deletedAt: ts('deleted_at'),
    lastSeenAt: ts('last_seen_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('users_email_idx').on(t.email), index('users_role_idx').on(t.role)],
);

export const sessions = sqliteTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    expiresAt: ts('expires_at').notNull(),
    token: text('token').notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('sessions_token_idx').on(t.token), index('sessions_user_idx').on(t.userId)],
);

export const accounts = sqliteTable(
  'accounts',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: ts('access_token_expires_at'),
    refreshTokenExpiresAt: ts('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('accounts_user_idx').on(t.userId)],
);

export const verifications = sqliteTable(
  'verifications',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: ts('expires_at').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('verifications_identifier_idx').on(t.identifier)],
);

export const addresses = sqliteTable(
  'addresses',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    label: text('label').notNull(),
    zoneId: text('zone_id'),
    area: text('area').notNull(),
    street: text('street').notNull(),
    building: text('building'),
    floor: text('floor'),
    notes: text('notes'),
    lat: real('lat'),
    lng: real('lng'),
    isDefault: bool('is_default').notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [index('addresses_user_idx').on(t.userId)],
);

export const favorites = sqliteTable(
  'favorites',
  {
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    itemId: text('item_id')
      .notNull()
      .references(() => menuItems.id, { onDelete: 'cascade' }),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.itemId] })],
);

// ————————————————————————————————————————————— branches & time —————————————————————————————————————————————

export interface ReservationSettings {
  slotIntervalMinutes: number;
  /** Turn time in minutes by party size; the largest key ≤ party size applies. */
  turnTimes: Record<string, number>;
  /** Max covers that may *start* in one slot (pacing). */
  maxCoversPerSlot: number;
  maxPartyOnline: number;
  /** Minutes before closing after which no seating starts. */
  lastSeatingBeforeCloseMinutes: number;
}

export interface OrderingSettings {
  /** Kitchen capacity: maximum orders promised in any window. */
  maxOrdersPerWindow: number;
  windowMinutes: number;
  basePrepMinutes: number;
  /** Extra minutes added while busy mode is on. */
  busyExtraMinutes: number;
  radiusKm: number | null;
}

export const branches = sqliteTable(
  'branches',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    name: localized('name').notNull(),
    shortName: localized('short_name').notNull(),
    city: localized('city').notNull(),
    district: localized('district').notNull(),
    address: localized('address').notNull(),
    story: localized('story'),
    timeZone: text('time_zone').notNull(),
    lat: real('lat').notNull(),
    lng: real('lng').notNull(),
    phone: text('phone').notNull(),
    whatsapp: text('whatsapp'),
    email: text('email').notNull(),
    parking: localized('parking'),
    accessibility: localized('accessibility'),
    heroImageId: text('hero_image_id'),
    reservationSettings: json<ReservationSettings>('reservation_settings').notNull(),
    orderingSettings: json<OrderingSettings>('ordering_settings').notNull(),
    reservationsEnabled: bool('reservations_enabled').notNull().default(true),
    deliveryEnabled: bool('delivery_enabled').notNull().default(true),
    pickupEnabled: bool('pickup_enabled').notNull().default(true),
    dineInEnabled: bool('dine_in_enabled').notNull().default(true),
    orderingPaused: bool('ordering_paused').notNull().default(false),
    busyMode: bool('busy_mode').notNull().default(false),
    isActive: bool('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('branches_slug_idx').on(t.slug)],
);

/** Weekly hours. `closes` may be earlier than `opens` for after-midnight service. */
export const openingHours = sqliteTable(
  'opening_hours',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    /** 'venue' = doors open; 'kitchen' = online ordering window. */
    kind: text('kind').$type<'venue' | 'kitchen'>().notNull().default('venue'),
    weekday: integer('weekday').notNull(), // 0 = Sunday
    opens: text('opens').notNull(),
    closes: text('closes').notNull(),
  },
  (t) => [index('opening_hours_branch_idx').on(t.branchId, t.kind, t.weekday)],
);

export interface TimeRange {
  opens: string;
  closes: string;
}

/** Holidays and exceptions for one local date. */
export const specialHours = sqliteTable(
  'special_hours',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    date: text('date').notNull(),
    label: localized('label').notNull(),
    closed: bool('closed').notNull().default(false),
    ranges: json<TimeRange[]>('ranges'),
    /** Blackout: venue open but no online reservations. */
    reservationsBlocked: bool('reservations_blocked').notNull().default(false),
  },
  (t) => [uniqueIndex('special_hours_branch_date_idx').on(t.branchId, t.date)],
);

/** Reservation service periods (e.g. breakfast, lunch, dinner). */
export const servicePeriods = sqliteTable(
  'service_periods',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    name: localized('name').notNull(),
    weekdays: json<number[]>('weekdays').notNull(),
    start: text('start').notNull(),
    /** Last seating time; may be past midnight ('01:00'). */
    end: text('end').notNull(),
    maxCoversPerSlot: integer('max_covers_per_slot'),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [index('service_periods_branch_idx').on(t.branchId)],
);

export const TABLE_AREAS = ['courtyard', 'liwan', 'roof', 'private'] as const;
export type TableArea = (typeof TABLE_AREAS)[number];

export const diningTables = sqliteTable(
  'dining_tables',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    code: text('code').notNull(),
    label: text('label').notNull(),
    area: text('area').$type<TableArea>().notNull(),
    minSeats: integer('min_seats').notNull(),
    maxSeats: integer('max_seats').notNull(),
    /** Tables sharing a group can be pushed together for larger parties. */
    combineGroup: text('combine_group'),
    reservable: bool('reservable').notNull().default(true),
    qrEnabled: bool('qr_enabled').notNull().default(true),
    isActive: bool('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [uniqueIndex('dining_tables_code_idx').on(t.code), index('dining_tables_branch_idx').on(t.branchId)],
);

export const deliveryZones = sqliteTable(
  'delivery_zones',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    name: localized('name').notNull(),
    kind: text('kind').$type<'area' | 'radius'>().notNull().default('area'),
    /** Districts served by an 'area' zone. */
    areas: json<LocalizedText[]>('areas'),
    radiusKm: real('radius_km'),
    fee: integer('fee').notNull(),
    minOrder: integer('min_order').notNull(),
    etaMinutes: integer('eta_minutes').notNull(),
    isActive: bool('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [index('delivery_zones_branch_idx').on(t.branchId)],
);

// ————————————————————————————————————————————— media —————————————————————————————————————————————

export interface MediaCredit {
  author: string;
  authorUrl?: string | null;
  source: string;
  sourceUrl?: string | null;
  license: string;
  licenseUrl?: string | null;
}

export const media = sqliteTable('media', {
  id: text('id').primaryKey(),
  /** Public path (e.g. /media/dish-foul.jpg) or storage key for uploads. */
  src: text('src').notNull(),
  kind: text('kind').$type<'image' | 'video'>().notNull().default('image'),
  width: integer('width').notNull(),
  height: integer('height').notNull(),
  blurDataUrl: text('blur_data_url'),
  focalX: real('focal_x').notNull().default(0.5),
  focalY: real('focal_y').notNull().default(0.5),
  alt: localized('alt').notNull(),
  credit: json<MediaCredit>('credit'),
  poster: text('poster'),
  sources: json<{ src: string; type: string }[]>('sources'),
  createdAt: createdAt(),
});

// ————————————————————————————————————————————— menu —————————————————————————————————————————————

export interface MenuWindow {
  weekdays: number[];
  start: string;
  end: string;
}

export const MENU_KINDS = ['breakfast', 'lunch', 'afternoon', 'dinner', 'tasting', 'desserts', 'drinks', 'kids', 'iftar', 'suhoor'] as const;
export type MenuKind = (typeof MENU_KINDS)[number];

export const menus = sqliteTable(
  'menus',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    kind: text('kind').$type<MenuKind>().notNull(),
    name: localized('name').notNull(),
    hour: localized('hour'),
    description: localized('description'),
    /** When the menu is served (branch-local time). Empty = all day. */
    schedule: json<MenuWindow[]>('schedule').notNull(),
    /** Null = every branch. */
    branchIds: json<string[] | null>('branch_ids'),
    /** Only visible while this seasonal mode is active. */
    seasonalModeId: text('seasonal_mode_id'),
    isTasting: bool('is_tasting').notNull().default(false),
    tastingPrice: integer('tasting_price'),
    imageId: text('image_id'),
    isActive: bool('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('menus_slug_idx').on(t.slug)],
);

export const menuCategories = sqliteTable(
  'menu_categories',
  {
    id: text('id').primaryKey(),
    menuId: text('menu_id')
      .notNull()
      .references(() => menus.id, { onDelete: 'cascade' }),
    slug: text('slug').notNull(),
    name: localized('name').notNull(),
    description: localized('description'),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [index('menu_categories_menu_idx').on(t.menuId)],
);

export const DIETARY_TAGS = ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'nut-free'] as const;
export type DietaryTag = (typeof DIETARY_TAGS)[number];

export const ALLERGENS = [
  'gluten',
  'crustaceans',
  'eggs',
  'fish',
  'peanuts',
  'soybeans',
  'milk',
  'nuts',
  'celery',
  'mustard',
  'sesame',
  'sulphites',
  'lupin',
  'molluscs',
] as const;
export type Allergen = (typeof ALLERGENS)[number];

export const menuItems = sqliteTable(
  'menu_items',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    name: localized('name').notNull(),
    description: localized('description').notNull(),
    story: localized('story'),
    ingredients: localized('ingredients'),
    price: integer('price').notNull(),
    calories: integer('calories'),
    spiceLevel: integer('spice_level').notNull().default(0),
    allergens: json<Allergen[]>('allergens').notNull(),
    dietary: json<DietaryTag[]>('dietary').notNull(),
    imageId: text('image_id'),
    isSignature: bool('is_signature').notNull().default(false),
    isAlcoholic: bool('is_alcoholic').notNull().default(false),
    /** Tasting courses are shown but not orderable on their own. */
    orderable: bool('orderable').notNull().default(true),
    /** Suggested for the "complete your meal" upsell. */
    upsell: bool('upsell').notNull().default(false),
    prepMinutes: integer('prep_minutes').notNull().default(15),
    pairings: json<string[]>('pairings'),
    tags: json<string[]>('tags'),
    /** Global availability (e.g. out of season). */
    isActive: bool('is_active').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('menu_items_slug_idx').on(t.slug)],
);

export const categoryItems = sqliteTable(
  'category_items',
  {
    categoryId: text('category_id')
      .notNull()
      .references(() => menuCategories.id, { onDelete: 'cascade' }),
    itemId: text('item_id')
      .notNull()
      .references(() => menuItems.id, { onDelete: 'cascade' }),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.categoryId, t.itemId] }), index('category_items_item_idx').on(t.itemId)],
);

/** Per-branch availability, live sold-out state and price overrides. */
export const itemBranches = sqliteTable(
  'item_branches',
  {
    itemId: text('item_id')
      .notNull()
      .references(() => menuItems.id, { onDelete: 'cascade' }),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    available: bool('available').notNull().default(true),
    soldOut: bool('sold_out').notNull().default(false),
    priceOverride: integer('price_override'),
    updatedAt: updatedAt(),
  },
  (t) => [primaryKey({ columns: [t.itemId, t.branchId] })],
);

export const modifierGroups = sqliteTable('modifier_groups', {
  id: text('id').primaryKey(),
  key: text('key').notNull(),
  name: localized('name').notNull(),
  minSelect: integer('min_select').notNull().default(0),
  maxSelect: integer('max_select').notNull().default(1),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const modifierOptions = sqliteTable(
  'modifier_options',
  {
    id: text('id').primaryKey(),
    groupId: text('group_id')
      .notNull()
      .references(() => modifierGroups.id, { onDelete: 'cascade' }),
    name: localized('name').notNull(),
    priceDelta: integer('price_delta').notNull().default(0),
    isDefault: bool('is_default').notNull().default(false),
    isAvailable: bool('is_available').notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [index('modifier_options_group_idx').on(t.groupId)],
);

export const itemModifierGroups = sqliteTable(
  'item_modifier_groups',
  {
    itemId: text('item_id')
      .notNull()
      .references(() => menuItems.id, { onDelete: 'cascade' }),
    groupId: text('group_id')
      .notNull()
      .references(() => modifierGroups.id, { onDelete: 'cascade' }),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.itemId, t.groupId] })],
);

// ————————————————————————————————————————————— reservations —————————————————————————————————————————————

export const RESERVATION_STATUSES = ['pending', 'confirmed', 'seated', 'completed', 'no_show', 'cancelled'] as const;
export type ReservationStatus = (typeof RESERVATION_STATUSES)[number];

export const reservations = sqliteTable(
  'reservations',
  {
    id: text('id').primaryKey(),
    code: text('code').notNull(),
    /** SHA-256 of the manage-link token (the token itself is only ever emailed). */
    tokenHash: text('token_hash').notNull(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id),
    userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
    /** Service day in branch-local time (after-midnight seatings belong to the previous day). */
    date: text('date').notNull(),
    time: text('time').notNull(),
    startsAt: ts('starts_at').notNull(),
    endsAt: ts('ends_at').notNull(),
    partySize: integer('party_size').notNull(),
    area: text('area').$type<TableArea | 'any'>().notNull().default('any'),
    occasion: text('occasion'),
    tableIds: json<string[]>('table_ids').notNull(),
    status: text('status').$type<ReservationStatus>().notNull().default('confirmed'),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone').notNull(),
    notes: text('notes'),
    dietaryNotes: text('dietary_notes'),
    staffNotes: text('staff_notes'),
    locale: text('locale').notNull().default('ar'),
    source: text('source').$type<'web' | 'admin' | 'phone' | 'concierge' | 'walk_in'>().notNull().default('web'),
    experienceId: text('experience_id'),
    depositAmount: integer('deposit_amount').notNull().default(0),
    depositStatus: text('deposit_status').$type<'none' | 'pending' | 'paid' | 'refunded'>().notNull().default('none'),
    paymentId: text('payment_id'),
    reminderSentAt: ts('reminder_sent_at'),
    seatedAt: ts('seated_at'),
    completedAt: ts('completed_at'),
    cancelledAt: ts('cancelled_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('reservations_code_idx').on(t.code),
    index('reservations_branch_date_idx').on(t.branchId, t.date),
    index('reservations_starts_idx').on(t.startsAt),
    index('reservations_user_idx').on(t.userId),
    index('reservations_email_idx').on(t.email),
  ],
);

/** Short-lived holds that keep a table while a guest completes the booking form. */
export const reservationHolds = sqliteTable(
  'reservation_holds',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    date: text('date').notNull(),
    time: text('time').notNull(),
    startsAt: ts('starts_at').notNull(),
    endsAt: ts('ends_at').notNull(),
    partySize: integer('party_size').notNull(),
    tableIds: json<string[]>('table_ids').notNull(),
    area: text('area').notNull().default('any'),
    sessionKey: text('session_key').notNull(),
    expiresAt: ts('expires_at').notNull(),
    createdAt: createdAt(),
  },
  (t) => [index('reservation_holds_branch_idx').on(t.branchId, t.date), index('reservation_holds_expires_idx').on(t.expiresAt)],
);

export const waitlistEntries = sqliteTable(
  'waitlist_entries',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    date: text('date').notNull(),
    preferredTime: text('preferred_time').notNull(),
    flexibleMinutes: integer('flexible_minutes').notNull().default(60),
    partySize: integer('party_size').notNull(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone').notNull(),
    notes: text('notes'),
    locale: text('locale').notNull().default('ar'),
    status: text('status').$type<'waiting' | 'offered' | 'booked' | 'expired' | 'cancelled'>().notNull().default('waiting'),
    reservationId: text('reservation_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('waitlist_branch_date_idx').on(t.branchId, t.date)],
);

// ————————————————————————————————————————————— ordering & payments —————————————————————————————————————————————

export const ORDER_STATUSES = ['pending_payment', 'placed', 'accepted', 'preparing', 'ready', 'out_for_delivery', 'completed', 'rejected', 'cancelled'] as const;
export type OrderStatus = (typeof ORDER_STATUSES)[number];
export type OrderChannel = 'delivery' | 'pickup' | 'dine_in';

export interface OrderAddress {
  zoneId: string | null;
  area: string;
  street: string;
  building?: string | null;
  floor?: string | null;
  notes?: string | null;
  lat?: number | null;
  lng?: number | null;
}

export interface SelectedModifier {
  groupId: string;
  optionId: string;
  name: LocalizedText;
  priceDelta: number;
}

export const orders = sqliteTable(
  'orders',
  {
    id: text('id').primaryKey(),
    number: text('number').notNull(),
    /** SHA-256 of the tracking token. */
    tokenHash: text('token_hash').notNull(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id),
    userId: text('user_id').references(() => users.id, { onDelete: 'set null' }),
    channel: text('channel').$type<OrderChannel>().notNull(),
    tableId: text('table_id'),
    status: text('status').$type<OrderStatus>().notNull().default('placed'),
    asap: bool('asap').notNull().default(true),
    scheduledFor: ts('scheduled_for'),
    promisedAt: ts('promised_at'),
    prepMinutes: integer('prep_minutes'),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone').notNull(),
    address: json<OrderAddress>('address'),
    zoneId: text('zone_id'),
    notes: text('notes'),
    locale: text('locale').notNull().default('ar'),
    subtotal: integer('subtotal').notNull(),
    discount: integer('discount').notNull().default(0),
    promoCode: text('promo_code'),
    deliveryFee: integer('delivery_fee').notNull().default(0),
    serviceCharge: integer('service_charge').notNull().default(0),
    tax: integer('tax').notNull().default(0),
    tip: integer('tip').notNull().default(0),
    giftCardAmount: integer('gift_card_amount').notNull().default(0),
    giftCardId: text('gift_card_id'),
    loyaltyPointsRedeemed: integer('loyalty_points_redeemed').notNull().default(0),
    loyaltyDiscount: integer('loyalty_discount').notNull().default(0),
    loyaltyPointsEarned: integer('loyalty_points_earned').notNull().default(0),
    total: integer('total').notNull(),
    paymentMethod: text('payment_method').$type<'card' | 'cash' | 'pay_at_venue' | 'gift_card'>().notNull(),
    paymentStatus: text('payment_status').$type<'pending' | 'authorized' | 'paid' | 'refunded' | 'failed' | 'unpaid'>().notNull().default('pending'),
    paymentId: text('payment_id'),
    rejectReason: text('reject_reason'),
    acceptedAt: ts('accepted_at'),
    readyAt: ts('ready_at'),
    completedAt: ts('completed_at'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('orders_number_idx').on(t.number),
    index('orders_branch_status_idx').on(t.branchId, t.status),
    index('orders_created_idx').on(t.createdAt),
    index('orders_user_idx').on(t.userId),
    index('orders_email_idx').on(t.email),
  ],
);

export const orderItems = sqliteTable(
  'order_items',
  {
    id: text('id').primaryKey(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    itemId: text('item_id').references(() => menuItems.id, { onDelete: 'set null' }),
    name: localized('name').notNull(),
    unitPrice: integer('unit_price').notNull(),
    quantity: integer('quantity').notNull(),
    modifiers: json<SelectedModifier[]>('modifiers').notNull(),
    notes: text('notes'),
    lineTotal: integer('line_total').notNull(),
  },
  (t) => [index('order_items_order_idx').on(t.orderId), index('order_items_item_idx').on(t.itemId)],
);

export const orderEvents = sqliteTable(
  'order_events',
  {
    id: text('id').primaryKey(),
    orderId: text('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    status: text('status').$type<OrderStatus>().notNull(),
    note: text('note'),
    actorId: text('actor_id'),
    at: createdAt(),
  },
  (t) => [index('order_events_order_idx').on(t.orderId)],
);

export interface CartLine {
  key: string;
  itemId: string;
  quantity: number;
  optionIds: string[];
  notes?: string;
}

/** Server-side carts for signed-in guests (anonymous carts live in the browser). */
export const carts = sqliteTable('carts', {
  userId: text('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  branchId: text('branch_id'),
  channel: text('channel').$type<OrderChannel>(),
  lines: json<CartLine[]>('lines').notNull(),
  updatedAt: updatedAt(),
});

export const payments = sqliteTable(
  'payments',
  {
    id: text('id').primaryKey(),
    provider: text('provider').notNull(),
    purpose: text('purpose').$type<'order' | 'deposit' | 'gift_card' | 'event'>().notNull(),
    referenceId: text('reference_id').notNull(),
    amount: integer('amount').notNull(),
    currency: text('currency').notNull(),
    status: text('status').$type<'requires_action' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'cancelled'>().notNull(),
    providerRef: text('provider_ref'),
    clientSecret: text('client_secret'),
    failureReason: text('failure_reason'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('payments_reference_idx').on(t.purpose, t.referenceId), index('payments_provider_ref_idx').on(t.providerRef)],
);

export const promotions = sqliteTable(
  'promotions',
  {
    id: text('id').primaryKey(),
    code: text('code').notNull(),
    description: localized('description').notNull(),
    kind: text('kind').$type<'percent' | 'fixed'>().notNull(),
    /** Percent (e.g. 15) or minor units for fixed. */
    value: integer('value').notNull(),
    maxDiscount: integer('max_discount'),
    minOrder: integer('min_order').notNull().default(0),
    startsAt: ts('starts_at'),
    endsAt: ts('ends_at'),
    usageLimit: integer('usage_limit'),
    perCustomerLimit: integer('per_customer_limit'),
    usedCount: integer('used_count').notNull().default(0),
    firstOrderOnly: bool('first_order_only').notNull().default(false),
    branchIds: json<string[] | null>('branch_ids'),
    channels: json<OrderChannel[] | null>('channels'),
    isActive: bool('is_active').notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('promotions_code_idx').on(t.code)],
);

export const promotionRedemptions = sqliteTable(
  'promotion_redemptions',
  {
    id: text('id').primaryKey(),
    promotionId: text('promotion_id')
      .notNull()
      .references(() => promotions.id, { onDelete: 'cascade' }),
    orderId: text('order_id').notNull(),
    email: text('email').notNull(),
    amount: integer('amount').notNull(),
    at: createdAt(),
  },
  (t) => [index('promotion_redemptions_promo_idx').on(t.promotionId, t.email)],
);

export const giftCards = sqliteTable(
  'gift_cards',
  {
    id: text('id').primaryKey(),
    code: text('code').notNull(),
    initialAmount: integer('initial_amount').notNull(),
    balance: integer('balance').notNull(),
    currency: text('currency').notNull(),
    design: text('design').notNull(),
    purchaserName: text('purchaser_name').notNull(),
    purchaserEmail: text('purchaser_email').notNull(),
    recipientName: text('recipient_name').notNull(),
    recipientEmail: text('recipient_email').notNull(),
    message: text('message'),
    locale: text('locale').notNull().default('ar'),
    deliverAt: ts('deliver_at'),
    deliveredAt: ts('delivered_at'),
    status: text('status').$type<'pending_payment' | 'scheduled' | 'active' | 'redeemed' | 'void' | 'expired'>().notNull(),
    expiresAt: ts('expires_at'),
    paymentId: text('payment_id'),
    userId: text('user_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('gift_cards_code_idx').on(t.code), index('gift_cards_recipient_idx').on(t.recipientEmail)],
);

export const giftCardTransactions = sqliteTable(
  'gift_card_transactions',
  {
    id: text('id').primaryKey(),
    giftCardId: text('gift_card_id')
      .notNull()
      .references(() => giftCards.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<'issue' | 'redeem' | 'refund' | 'adjust' | 'void'>().notNull(),
    amount: integer('amount').notNull(),
    orderId: text('order_id'),
    note: text('note'),
    actorId: text('actor_id'),
    at: createdAt(),
  },
  (t) => [index('gift_card_tx_card_idx').on(t.giftCardId)],
);

export const loyaltyRewards = sqliteTable('loyalty_rewards', {
  id: text('id').primaryKey(),
  name: localized('name').notNull(),
  description: localized('description'),
  pointsCost: integer('points_cost').notNull(),
  /** Discount in minor units granted at checkout. */
  value: integer('value').notNull(),
  minTier: text('min_tier'),
  isActive: bool('is_active').notNull().default(true),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const loyaltyTransactions = sqliteTable(
  'loyalty_transactions',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<'earn' | 'redeem' | 'adjust' | 'bonus' | 'reverse'>().notNull(),
    points: integer('points').notNull(),
    orderId: text('order_id'),
    rewardId: text('reward_id'),
    note: text('note'),
    at: createdAt(),
  },
  (t) => [index('loyalty_tx_user_idx').on(t.userId)],
);

// ————————————————————————————————————————————— experiences & events —————————————————————————————————————————————

export const events = sqliteTable(
  'events',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    kind: text('kind').$type<'chefs_table' | 'tasting' | 'class' | 'gathering'>().notNull(),
    title: localized('title').notNull(),
    summary: localized('summary').notNull(),
    body: localized('body'),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id),
    startsAt: ts('starts_at').notNull(),
    endsAt: ts('ends_at').notNull(),
    capacity: integer('capacity').notNull(),
    imageId: text('image_id'),
    isPublished: bool('is_published').notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('events_slug_idx').on(t.slug), index('events_starts_idx').on(t.startsAt)],
);

export const eventTicketTypes = sqliteTable(
  'event_ticket_types',
  {
    id: text('id').primaryKey(),
    eventId: text('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    name: localized('name').notNull(),
    description: localized('description'),
    price: integer('price').notNull(),
    capacity: integer('capacity'),
    sortOrder: integer('sort_order').notNull().default(0),
  },
  (t) => [index('event_ticket_types_event_idx').on(t.eventId)],
);

export const eventBookings = sqliteTable(
  'event_bookings',
  {
    id: text('id').primaryKey(),
    code: text('code').notNull(),
    eventId: text('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    ticketTypeId: text('ticket_type_id')
      .notNull()
      .references(() => eventTicketTypes.id),
    quantity: integer('quantity').notNull(),
    total: integer('total').notNull(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone').notNull(),
    locale: text('locale').notNull().default('ar'),
    userId: text('user_id'),
    status: text('status').$type<'pending_payment' | 'confirmed' | 'checked_in' | 'cancelled'>().notNull(),
    paymentId: text('payment_id'),
    checkedInAt: ts('checked_in_at'),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('event_bookings_code_idx').on(t.code), index('event_bookings_event_idx').on(t.eventId)],
);

export const privateRooms = sqliteTable('private_rooms', {
  id: text('id').primaryKey(),
  slug: text('slug').notNull(),
  branchId: text('branch_id')
    .notNull()
    .references(() => branches.id, { onDelete: 'cascade' }),
  name: localized('name').notNull(),
  description: localized('description').notNull(),
  seated: integer('seated').notNull(),
  standing: integer('standing'),
  features: json<LocalizedText[]>('features'),
  imageId: text('image_id'),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const privatePackages = sqliteTable('private_packages', {
  id: text('id').primaryKey(),
  name: localized('name').notNull(),
  description: localized('description').notNull(),
  pricePerGuest: integer('price_per_guest').notNull(),
  minGuests: integer('min_guests').notNull(),
  kind: text('kind').$type<'private_dining' | 'catering'>().notNull().default('private_dining'),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const inquiries = sqliteTable(
  'inquiries',
  {
    id: text('id').primaryKey(),
    kind: text('kind').$type<'private_dining' | 'catering' | 'contact' | 'press' | 'large_party'>().notNull(),
    branchId: text('branch_id'),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone'),
    date: text('date'),
    guests: integer('guests'),
    packageId: text('package_id'),
    message: text('message').notNull(),
    locale: text('locale').notNull().default('ar'),
    status: text('status').$type<'new' | 'in_progress' | 'won' | 'lost' | 'closed'>().notNull().default('new'),
    staffNotes: text('staff_notes'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index('inquiries_status_idx').on(t.status, t.kind)],
);

// ————————————————————————————————————————————— content —————————————————————————————————————————————

export const reviews = sqliteTable(
  'reviews',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id'),
    userId: text('user_id'),
    name: text('name').notNull(),
    email: text('email'),
    rating: integer('rating').notNull(),
    title: text('title'),
    body: text('body').notNull(),
    locale: text('locale').notNull(),
    visitDate: text('visit_date'),
    status: text('status').$type<'pending' | 'published' | 'rejected'>().notNull().default('pending'),
    response: localized('response'),
    featured: bool('featured').notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [index('reviews_status_idx').on(t.status)],
);

export const pressItems = sqliteTable('press_items', {
  id: text('id').primaryKey(),
  kind: text('kind').$type<'press' | 'award'>().notNull(),
  publication: localized('publication').notNull(),
  title: localized('title').notNull(),
  quote: localized('quote').notNull(),
  year: integer('year').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const faqs = sqliteTable('faqs', {
  id: text('id').primaryKey(),
  category: text('category').notNull(),
  question: localized('question').notNull(),
  answer: localized('answer').notNull(),
  sortOrder: integer('sort_order').notNull().default(0),
});

export const teamMembers = sqliteTable('team_members', {
  id: text('id').primaryKey(),
  name: localized('name').notNull(),
  role: localized('role').notNull(),
  bio: localized('bio').notNull(),
  imageId: text('image_id'),
  branchId: text('branch_id'),
  sortOrder: integer('sort_order').notNull().default(0),
});

export interface RecipeData {
  serves: number;
  minutes: number;
  ingredients: LocalizedText[];
  steps: LocalizedText[];
}

export const journalPosts = sqliteTable(
  'journal_posts',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    kind: text('kind').$type<'article' | 'recipe'>().notNull(),
    title: localized('title').notNull(),
    excerpt: localized('excerpt').notNull(),
    /** Sanitised HTML per locale (authored in the admin's rich-text editor). */
    body: localized('body').notNull(),
    coverImageId: text('cover_image_id'),
    author: localized('author').notNull(),
    readingMinutes: integer('reading_minutes').notNull().default(4),
    recipe: json<RecipeData>('recipe'),
    publishedAt: ts('published_at'),
    isPublished: bool('is_published').notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('journal_posts_slug_idx').on(t.slug), index('journal_posts_published_idx').on(t.publishedAt)],
);

export const galleryItems = sqliteTable('gallery_items', {
  id: text('id').primaryKey(),
  mediaId: text('media_id')
    .notNull()
    .references(() => media.id, { onDelete: 'cascade' }),
  caption: localized('caption'),
  hour: text('hour'),
  sortOrder: integer('sort_order').notNull().default(0),
});

/** Editable page copy: one row per page section, JSON fields per locale. */
export const contentBlocks = sqliteTable(
  'content_blocks',
  {
    id: text('id').primaryKey(),
    page: text('page').notNull(),
    key: text('key').notNull(),
    data: json<Record<string, LocalizedText | string | number | boolean | null>>('data').notNull(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('content_blocks_page_key_idx').on(t.page, t.key)],
);

export const jobPostings = sqliteTable(
  'job_postings',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    title: localized('title').notNull(),
    branchId: text('branch_id'),
    employment: text('employment').$type<'full_time' | 'part_time' | 'seasonal'>().notNull(),
    summary: localized('summary').notNull(),
    description: localized('description').notNull(),
    isOpen: bool('is_open').notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('job_postings_slug_idx').on(t.slug)],
);

export const jobApplications = sqliteTable(
  'job_applications',
  {
    id: text('id').primaryKey(),
    postingId: text('posting_id')
      .notNull()
      .references(() => jobPostings.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    email: text('email').notNull(),
    phone: text('phone').notNull(),
    message: text('message'),
    cvKey: text('cv_key').notNull(),
    cvName: text('cv_name').notNull(),
    status: text('status').$type<'new' | 'reviewing' | 'interview' | 'hired' | 'declined'>().notNull().default('new'),
    locale: text('locale').notNull().default('ar'),
    createdAt: createdAt(),
  },
  (t) => [index('job_applications_posting_idx').on(t.postingId)],
);

export const newsletterSubscribers = sqliteTable(
  'newsletter_subscribers',
  {
    id: text('id').primaryKey(),
    email: text('email').notNull(),
    locale: text('locale').notNull().default('ar'),
    status: text('status').$type<'pending' | 'confirmed' | 'unsubscribed'>().notNull().default('pending'),
    tokenHash: text('token_hash').notNull(),
    source: text('source'),
    confirmedAt: ts('confirmed_at'),
    unsubscribedAt: ts('unsubscribed_at'),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('newsletter_email_idx').on(t.email)],
);

export const seasonalModes = sqliteTable(
  'seasonal_modes',
  {
    id: text('id').primaryKey(),
    slug: text('slug').notNull(),
    kind: text('kind').$type<'ramadan' | 'eid' | 'new_year' | 'national_day' | 'custom'>().notNull(),
    name: localized('name').notNull(),
    banner: localized('banner'),
    /** Local dates (flagship branch zone), inclusive. */
    startDate: text('start_date').notNull(),
    endDate: text('end_date').notNull(),
    /** Visual layer key: 'ramadan' | 'eid' | 'new_year' | 'none'. */
    theme: text('theme').notNull().default('none'),
    /** Replacement weekly hours per branch while active: { [branchId]: TimeRange[] }. */
    hours: json<Record<string, TimeRange[]>>('hours'),
    isEnabled: bool('is_enabled').notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => [uniqueIndex('seasonal_modes_slug_idx').on(t.slug)],
);

// ————————————————————————————————————————————— operations —————————————————————————————————————————————

export const tableRequests = sqliteTable(
  'table_requests',
  {
    id: text('id').primaryKey(),
    branchId: text('branch_id')
      .notNull()
      .references(() => branches.id, { onDelete: 'cascade' }),
    tableId: text('table_id')
      .notNull()
      .references(() => diningTables.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<'waiter' | 'bill'>().notNull(),
    note: text('note'),
    status: text('status').$type<'open' | 'acknowledged' | 'done'>().notNull().default('open'),
    acknowledgedBy: text('acknowledged_by'),
    acknowledgedAt: ts('acknowledged_at'),
    doneAt: ts('done_at'),
    createdAt: createdAt(),
  },
  (t) => [index('table_requests_branch_status_idx').on(t.branchId, t.status)],
);

export const notifications = sqliteTable(
  'notifications',
  {
    id: text('id').primaryKey(),
    /** Target role (all staff with it see the notification) or a specific user. */
    role: text('role'),
    userId: text('user_id'),
    branchId: text('branch_id'),
    kind: text('kind').notNull(),
    title: localized('title').notNull(),
    body: localized('body'),
    href: text('href'),
    readBy: json<string[]>('read_by').notNull(),
    createdAt: createdAt(),
  },
  (t) => [index('notifications_created_idx').on(t.createdAt)],
);

export const auditLogs = sqliteTable(
  'audit_logs',
  {
    id: text('id').primaryKey(),
    actorId: text('actor_id'),
    actorEmail: text('actor_email'),
    action: text('action').notNull(),
    entity: text('entity').notNull(),
    entityId: text('entity_id'),
    summary: text('summary'),
    diff: json<Record<string, unknown>>('diff'),
    ip: text('ip'),
    at: createdAt(),
  },
  (t) => [index('audit_logs_at_idx').on(t.at), index('audit_logs_entity_idx').on(t.entity, t.entityId)],
);

export const emailOutbox = sqliteTable(
  'email_outbox',
  {
    id: text('id').primaryKey(),
    to: text('to').notNull(),
    subject: text('subject').notNull(),
    html: text('html').notNull(),
    text: text('text').notNull(),
    template: text('template').notNull(),
    locale: text('locale').notNull(),
    meta: json<Record<string, string | number | boolean | null>>('meta'),
    provider: text('provider').notNull(),
    status: text('status').$type<'sent' | 'failed' | 'captured'>().notNull(),
    error: text('error'),
    createdAt: createdAt(),
  },
  (t) => [index('email_outbox_created_idx').on(t.createdAt)],
);

export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value', { mode: 'json' }).$type<unknown>().notNull(),
  updatedAt: updatedAt(),
});

export const analyticsEvents = sqliteTable(
  'analytics_events',
  {
    id: text('id').primaryKey(),
    /** Daily-rotating, salted hash — never an IP or a cookie. */
    visitor: text('visitor').notNull(),
    name: text('name').notNull(),
    path: text('path').notNull(),
    locale: text('locale'),
    referrer: text('referrer'),
    device: text('device'),
    meta: json<Record<string, string | number>>('meta'),
    at: createdAt(),
  },
  (t) => [index('analytics_at_idx').on(t.at), index('analytics_name_idx').on(t.name, t.at)],
);

export const rateLimits = sqliteTable('rate_limits', {
  key: text('key').primaryKey(),
  count: integer('count').notNull(),
  resetAt: integer('reset_at').notNull(),
});

export const files = sqliteTable('files', {
  id: text('id').primaryKey(),
  key: text('key').notNull(),
  name: text('name').notNull(),
  mime: text('mime').notNull(),
  size: integer('size').notNull(),
  purpose: text('purpose').$type<'media' | 'cv' | 'document'>().notNull(),
  ownerId: text('owner_id'),
  isPublic: bool('is_public').notNull().default(false),
  createdAt: createdAt(),
});
