import {
  Award,
  BadgePercent,
  Bell,
  BookOpenText,
  BriefcaseBusiness,
  CalendarDays,
  ChartColumn,
  ChefHat,
  DoorOpen,
  Gift,
  HandPlatter,
  Images,
  Inbox,
  LayoutDashboard,
  LayoutTemplate,
  Mail,
  MailOpen,
  MapPin,
  MessageSquareQuote,
  MoonStar,
  NotebookPen,
  ReceiptText,
  ScrollText,
  Settings,
  Ticket,
  UserCog,
  Users,
  type LucideIcon,
} from 'lucide-react';
import type { AdminNavIcon } from '@/lib/admin/nav';

export const NAV_ICONS: Record<AdminNavIcon, LucideIcon> = {
  dashboard: LayoutDashboard,
  orders: ReceiptText,
  kds: ChefHat,
  reservations: CalendarDays,
  tables: HandPlatter,
  menu: BookOpenText,
  customers: Users,
  reviews: MessageSquareQuote,
  inquiries: Inbox,
  newsletter: Mail,
  events: Ticket,
  giftCards: Gift,
  promotions: BadgePercent,
  loyalty: Award,
  content: LayoutTemplate,
  journal: NotebookPen,
  media: Images,
  privateDining: DoorOpen,
  careers: BriefcaseBusiness,
  locations: MapPin,
  seasonal: MoonStar,
  reports: ChartColumn,
  settings: Settings,
  staff: UserCog,
  notifications: Bell,
  audit: ScrollText,
  outbox: MailOpen,
};
