/**
 * The Zill menu: nine menus organised by the hours of the day. Written natively in Arabic and English.
 * Prices are in riyals here (converted to halalas by the seed). The beverage programme is alcohol-free.
 */
import type { Allergen, DietaryTag, MenuKind } from '../../../src/lib/db/schema';
import type { BranchSlug, L } from './types';

export interface SeedModifierGroup {
  key: string;
  name: L;
  min: number;
  max: number;
  options: { key: string; name: L; delta: number; default?: boolean }[];
}

export interface SeedItem {
  slug: string;
  name: L;
  description: L;
  story?: L;
  ingredients?: L;
  price: number;
  calories?: number;
  spice?: number;
  allergens: Allergen[];
  dietary: DietaryTag[];
  modifiers?: string[];
  pairings?: string[];
  signature?: boolean;
  upsell?: boolean;
  prep?: number;
  image: string;
  branches?: BranchSlug[];
  orderable?: boolean;
  tags?: string[];
}

export interface SeedMenu {
  slug: string;
  kind: MenuKind;
  name: L;
  hour: L;
  description: L;
  schedule: { weekdays: number[]; start: string; end: string }[];
  tastingPrice?: number;
  isTasting?: boolean;
  image?: string;
  categories: { slug: string; name: L; description?: L; items: string[] }[];
}

const EVERY_DAY = [0, 1, 2, 3, 4, 5, 6];

export const modifierGroups: SeedModifierGroup[] = [
  {
    key: 'foul-style',
    name: { ar: 'على طريقتك', en: 'Your way' },
    min: 0,
    max: 3,
    options: [
      { key: 'ghee', name: { ar: 'بالسمن البلدي', en: 'With ghee' }, delta: 3 },
      { key: 'tahini', name: { ar: 'بالطحينة', en: 'With tahini' }, delta: 2 },
      { key: 'chilli', name: { ar: 'بالفلفل الأخضر', en: 'With green chilli' }, delta: 0 },
      { key: 'egg', name: { ar: 'مع بيضة مسلوقة', en: 'With a boiled egg' }, delta: 4 },
    ],
  },
  {
    key: 'bread-extra',
    name: { ar: 'خبز إضافي', en: 'More bread' },
    min: 0,
    max: 2,
    options: [
      { key: 'tamees', name: { ar: 'تميس', en: 'Tamees' }, delta: 5 },
      { key: 'saj', name: { ar: 'خبز صاج', en: 'Saj bread' }, delta: 4 },
      { key: 'tannour', name: { ar: 'خبز التنّور', en: 'Tannour bread' }, delta: 4 },
    ],
  },
  {
    key: 'egg-count',
    name: { ar: 'عدد البيض', en: 'Eggs' },
    min: 1,
    max: 1,
    options: [
      { key: 'two', name: { ar: 'بيضتان', en: 'Two eggs' }, delta: 0, default: true },
      { key: 'three', name: { ar: 'ثلاث بيضات', en: 'Three eggs' }, delta: 6 },
    ],
  },
  {
    key: 'mutabbaq-filling',
    name: { ar: 'الحشوة', en: 'Filling' },
    min: 1,
    max: 1,
    options: [
      { key: 'beef', name: { ar: 'لحم وبيض وكرّاث', en: 'Beef, egg & leek' }, delta: 0, default: true },
      { key: 'cheese', name: { ar: 'جبن وبيض', en: 'Cheese & egg' }, delta: 0 },
      { key: 'banana', name: { ar: 'موز وعسل', en: 'Banana & honey' }, delta: 2 },
    ],
  },
  {
    key: 'manakish-extras',
    name: { ar: 'إضافات', en: 'Extras' },
    min: 0,
    max: 2,
    options: [
      { key: 'zaatar-half', name: { ar: 'نصفها بالزعتر', en: "Half za'atar" }, delta: 0 },
      { key: 'more-cheese', name: { ar: 'عكّاوي إضافي', en: 'Extra akkawi' }, delta: 6 },
      { key: 'tomato-mint', name: { ar: 'طماطم ونعناع', en: 'Tomato & mint' }, delta: 2 },
    ],
  },
  {
    key: 'bread-basket',
    name: { ar: 'خبز', en: 'Bread' },
    min: 0,
    max: 1,
    options: [{ key: 'basket', name: { ar: 'سلّة خبز دافئ', en: 'Basket of warm bread' }, delta: 8 }],
  },
  {
    key: 'ghee-extra',
    name: { ar: 'إضافة', en: 'Add' },
    min: 0,
    max: 1,
    options: [{ key: 'ghee', name: { ar: 'ملعقة سمن إضافية', en: 'An extra spoon of ghee' }, delta: 3 }],
  },
  {
    key: 'kabsa-extras',
    name: { ar: 'إضافات', en: 'Extras' },
    min: 0,
    max: 3,
    options: [
      { key: 'more-lamb', name: { ar: 'لحم إضافي', en: 'More lamb' }, delta: 40 },
      { key: 'daqqus', name: { ar: 'دقّوس الطماطم', en: 'Tomato daqqus' }, delta: 4 },
      { key: 'nuts', name: { ar: 'لوز وزبيب إضافي', en: 'More almonds & raisins' }, delta: 6 },
    ],
  },
  {
    key: 'side-choice',
    name: { ar: 'يُقدَّم مع', en: 'Served with' },
    min: 1,
    max: 1,
    options: [
      { key: 'rice', name: { ar: 'أرزّ بالزعفران', en: 'Saffron rice' }, delta: 0, default: true },
      { key: 'bread', name: { ar: 'خبز التنّور', en: 'Tannour bread' }, delta: 0 },
      { key: 'fattoush', name: { ar: 'فتّوش', en: 'Fattoush' }, delta: 8 },
    ],
  },
  {
    key: 'doneness',
    name: { ar: 'درجة الاستواء', en: 'Cooked' },
    min: 1,
    max: 1,
    options: [
      { key: 'medium', name: { ar: 'متوسّط', en: 'Medium' }, delta: 0, default: true },
      { key: 'medium-well', name: { ar: 'فوق المتوسّط', en: 'Medium-well' }, delta: 0 },
      { key: 'well', name: { ar: 'مستوٍ تماماً', en: 'Well done' }, delta: 0 },
    ],
  },
  {
    key: 'coffee-roast',
    name: { ar: 'التحميصة', en: 'Roast' },
    min: 1,
    max: 1,
    options: [
      { key: 'blonde', name: { ar: 'شقراء', en: 'Blonde (light)' }, delta: 0, default: true },
      { key: 'red', name: { ar: 'حمراء', en: 'Red (medium)' }, delta: 0 },
    ],
  },
  {
    key: 'sweetness',
    name: { ar: 'السكّر', en: 'Sugar' },
    min: 1,
    max: 1,
    options: [
      { key: 'regular', name: { ar: 'عادي', en: 'Regular' }, delta: 0, default: true },
      { key: 'light', name: { ar: 'خفيف', en: 'Light' }, delta: 0 },
      { key: 'none', name: { ar: 'بلا سكّر', en: 'No sugar' }, delta: 0 },
    ],
  },
  {
    key: 'cooler-size',
    name: { ar: 'الحجم', en: 'Size' },
    min: 1,
    max: 1,
    options: [
      { key: 'glass', name: { ar: 'كوب', en: 'Glass' }, delta: 0, default: true },
      { key: 'jug', name: { ar: 'إبريق لأربعة', en: 'Jug for four' }, delta: 48 },
    ],
  },
];

export const items: SeedItem[] = [
  // ——————————————————————————— Morning shade ———————————————————————————
  {
    slug: 'tamees-foul',
    name: { ar: 'فول وتميس', en: 'Foul & tamees' },
    description: {
      ar: 'فولٌ مطبوخ على مهلٍ طوال الليل، يُهرَس بالكمّون والليمون وزيت الزيتون، ويُقدَّم مع تميسٍ ساخنٍ من الفرن.',
      en: 'Fava beans cooked overnight, crushed with cumin, lemon and olive oil, with tamees torn warm from the oven.',
    },
    story: {
      ar: 'فطور جدّة منذ زمن قوافل الحجّاج. يوضع القِدر على النار عند منتصف الليل، وعند السابعة تلين الحبّات تحت الملعقة.',
      en: "Jeddah's breakfast since the pilgrims' caravans. The pot goes on at midnight; by seven the beans give way under a spoon.",
    },
    ingredients: {
      ar: 'فول، كمّون، ثوم، ليمون، زيت زيتون، طماطم، فلفل أخضر، خبز تميس',
      en: 'Fava beans, cumin, garlic, lemon, olive oil, tomato, green chilli, tamees bread',
    },
    price: 38,
    calories: 520,
    spice: 1,
    allergens: ['gluten'],
    dietary: ['vegan', 'dairy-free', 'nut-free'],
    modifiers: ['foul-style', 'bread-extra'],
    pairings: ['karak-chai', 'mint-tea'],
    signature: true,
    image: 'dish-tamees-foul',
  },
  {
    slug: 'shakshuka-loomi',
    name: { ar: 'شكشوكة باللومي', en: 'Shakshuka with dried lime' },
    description: {
      ar: 'بيضٌ ينضج في صلصة طماطم وفلفل مطهوّة على مهل، يوقظها اللومي الأسود، وتُختم بالكزبرة.',
      en: 'Eggs set in a slow tomato and pepper sauce, sharpened with black loomi and finished with coriander.',
    },
    story: {
      ar: 'اللومي حموضة الخليج الهادئة. نطحنه أمامك فتصل رائحته قبل المقلاة.',
      en: "Dried lime is the Gulf's quiet sourness. We grind it at the table, so the smell arrives before the pan does.",
    },
    ingredients: {
      ar: 'بيض، طماطم، فلفل أحمر، بصل، ثوم، لومي أسود، كمّون، كزبرة، زيت زيتون',
      en: 'Eggs, tomato, red pepper, onion, garlic, black dried lime, cumin, coriander, olive oil',
    },
    price: 46,
    calories: 480,
    spice: 1,
    allergens: ['eggs'],
    dietary: ['vegetarian', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['egg-count', 'bread-extra'],
    pairings: ['labneh-zaatar', 'hibiscus-cooler'],
    image: 'dish-shakshuka-loomi',
  },
  {
    slug: 'balaleet',
    name: { ar: 'بلاليط', en: 'Balaleet' },
    description: {
      ar: 'شعيريّة محلّاة بالزعفران والهيل وماء الورد، تحت عجّةٍ رقيقة مالحة.',
      en: 'Vermicelli sweetened with saffron, cardamom and rose water, under a thin, savoury omelette.',
    },
    story: {
      ar: 'الحلو والمالح في طبقٍ واحد؛ فطورٌ خليجيّ يصبح منطقياً تماماً عند الملعقة الثانية.',
      en: 'Sweet and salt on one plate — a Gulf breakfast that makes perfect sense by the second spoonful.',
    },
    ingredients: { ar: 'شعيرية، زعفران، هيل، ماء ورد، سكّر، سمن، بيض', en: 'Vermicelli, saffron, cardamom, rose water, sugar, ghee, eggs' },
    price: 42,
    calories: 610,
    allergens: ['gluten', 'eggs', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['karak-chai'],
    image: 'dish-balaleet',
  },
  {
    slug: 'mutabbaq',
    name: { ar: 'مطبّق', en: 'Mutabbaq' },
    description: {
      ar: 'عجينةٌ رقيقة كالورق تُطوى على البيض والكرّاث واللحم المفروم المتبّل، وتُحمَّص على الصاج الحديدي.',
      en: 'Paper-thin dough folded around egg, leek and spiced minced beef, crisped on the iron griddle.',
    },
    story: {
      ar: 'تُمدّ العجينة باليد حتى تكاد تقرأ من خلالها؛ حيلةٌ تعلّمها طهاتنا في أزقّة البلد.',
      en: 'The dough is stretched by hand until you could almost read through it — a trick our cooks learned in the lanes of Al-Balad.',
    },
    ingredients: { ar: 'عجينة قمح، بيض، لحم مفروم، كرّاث، بصل، فلفل أسود، سمن', en: 'Wheat dough, eggs, minced beef, leek, onion, black pepper, ghee' },
    price: 44,
    calories: 690,
    spice: 1,
    allergens: ['gluten', 'eggs', 'milk'],
    dietary: ['nut-free'],
    modifiers: ['mutabbaq-filling'],
    pairings: ['karak-chai', 'tamees-foul'],
    image: 'dish-mutabbaq',
  },
  {
    slug: 'masoub',
    name: { ar: 'معصوب', en: 'Masoub' },
    description: {
      ar: 'موزٌ ناضج يُهرَس مع خبزٍ دافئ وسمنٍ وعسل، وتعلوه قشطةٌ وحبّاتٌ من التمر.',
      en: 'Ripe banana crushed into warm flatbread with ghee and honey, topped with cream and a few dates.',
    },
    story: {
      ar: 'طعام المسافرين الذي صار طعام الطمأنينة: مُشبعٌ وحلو، ويسبق حرّ النهار بزمن.',
      en: "Travellers' food turned comfort food: filling, sweet and ready long before the heat.",
    },
    ingredients: { ar: 'خبز، موز، سمن، عسل، قشطة، تمر', en: 'Flatbread, banana, ghee, honey, cream, dates' },
    price: 39,
    calories: 720,
    allergens: ['gluten', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['saudi-coffee'],
    image: 'dish-masoub',
  },
  {
    slug: 'areeka',
    name: { ar: 'عريكة بعسل السدر', en: 'Areeka with sidr honey' },
    description: {
      ar: 'خبزٌ أسمر يُعرَك باليد مع السمن والتمر، ويُتوَّج بعسل السدر من الباحة.',
      en: 'Brown bread worked by hand with ghee and dates, crowned with sidr honey from Al-Baha.',
    },
    story: {
      ar: 'في جبال الجنوب تُقدَّم العريكة صباحَ الضيوف. نحافظ على شكلها: حفرةٌ في وسطها يتجمّع فيها العسل.',
      en: 'In the southern mountains, areeka means guests are here. We keep its shape — a crater in the middle for the honey to pool in.',
    },
    ingredients: { ar: 'خبز بُرّ، سمن، تمر، عسل سدر، حبّة البركة', en: 'Wholewheat bread, ghee, dates, sidr honey, nigella seeds' },
    price: 48,
    calories: 780,
    allergens: ['gluten', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['saudi-coffee', 'khawlani-pour-over'],
    signature: true,
    image: 'dish-areeka',
  },
  {
    slug: 'labneh-zaatar',
    name: { ar: 'لبنة وزعتر وصاج', en: "Labneh, za'atar & saj" },
    description: {
      ar: 'لبنةٌ مصفّاة في بركةٍ من زيت الزيتون مع زعترٍ بريّ وزيتون وخيار، وخبز صاجٍ من القبّة الحديدية.',
      en: "Strained labneh in a well of olive oil with wild za'atar, olives and cucumber, and saj bread from the iron dome.",
    },
    ingredients: {
      ar: 'لبنة، زيت زيتون، زعتر، سمسم، سمّاق، زيتون، خيار، نعناع، خبز صاج',
      en: "Labneh, olive oil, za'atar, sesame, sumac, olives, cucumber, mint, saj bread",
    },
    price: 36,
    calories: 540,
    allergens: ['milk', 'gluten', 'sesame'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['mint-tea', 'shakshuka-loomi'],
    image: 'dish-labneh-zaatar',
  },
  {
    slug: 'akkawi-manakish',
    name: { ar: 'منقوشة عكّاوي بحبّة البركة', en: 'Akkawi manakish with nigella' },
    description: {
      ar: 'خبز التنّور تحت جبنة عكّاوي ذائبة وحبّة البركة ونثرةٍ من النعناع الطازج.',
      en: 'Tannour flatbread under melting akkawi, nigella seeds and a scatter of fresh mint.',
    },
    ingredients: { ar: 'عجينة قمح، جبنة عكّاوي، موزاريلا، حبّة البركة، نعناع', en: 'Wheat dough, akkawi cheese, mozzarella, nigella seeds, mint' },
    price: 32,
    calories: 650,
    allergens: ['gluten', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    modifiers: ['manakish-extras'],
    pairings: ['karak-chai'],
    image: 'dish-akkawi-manakish',
  },
  {
    slug: 'eggs-east-wall',
    name: { ar: 'بيض الجدار الشرقي', en: 'Eggs by the east wall' },
    description: {
      ar: 'بيضتان مقليّتان في طماطم متبّلة مع شرائح سجقٍ بقري، ورشّة كمّون، وخبز صاجٍ دافئ.',
      en: 'Two fried eggs in spiced tomato with slices of beef sujuk, a pinch of cumin and warm saj.',
    },
    story: {
      ar: 'سُمّي على اسم الطاولة التي تسقط عليها أول شمس. ينفد قبل العاشرة في الصباحات الباردة.',
      en: 'Named for the table where the first sun lands. On cool mornings it is gone by ten.',
    },
    ingredients: { ar: 'بيض، سجق بقري، طماطم، ثوم، كمّون، بقدونس، خبز صاج', en: 'Eggs, beef sujuk, tomato, garlic, cumin, parsley, saj bread' },
    price: 44,
    calories: 590,
    spice: 1,
    allergens: ['eggs', 'gluten'],
    dietary: ['dairy-free', 'nut-free'],
    modifiers: ['bread-extra'],
    pairings: ['karak-chai', 'labneh-zaatar'],
    image: 'dish-eggs-east-wall',
  },
  {
    slug: 'dates-laban',
    name: { ar: 'تمر القصيم وفاكهة ولبن', en: 'Qassim dates, fruit & laban' },
    description: {
      ar: 'رُطَب هذا الصباح وحبّات تمرٍ من عنيزة، وفاكهة الموسم، وكوبٌ باردٌ من اللبن.',
      en: "This morning's rutab and a few dried dates from Unaizah, the season's fruit and a cold cup of laban.",
    },
    ingredients: { ar: 'رطب وتمر، فاكهة موسمية، لبن، نعناع', en: 'Rutab and dates, seasonal fruit, laban, mint' },
    price: 34,
    calories: 380,
    allergens: ['milk'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    pairings: ['saudi-coffee'],
    image: 'dish-dates-laban',
  },

  // ——————————————————————————— The short shade ———————————————————————————
  {
    slug: 'hummus-ghee',
    name: { ar: 'حمّص بالسمن والصنوبر', en: 'Hummus with ghee & pine nuts' },
    description: {
      ar: 'حمّصٌ مخفوق بالطحينة والليمون، يُسكب فوقه السمن الحار مع صنوبرٍ محمّص ورشّة كمّون.',
      en: 'Chickpeas whipped with tahini and lemon, under hot ghee, toasted pine nuts and a dust of cumin.',
    },
    ingredients: { ar: 'حمّص، طحينة، ليمون، ثوم، سمن، صنوبر، كمّون، بابريكا', en: 'Chickpeas, tahini, lemon, garlic, ghee, pine nuts, cumin, paprika' },
    price: 34,
    calories: 460,
    allergens: ['sesame', 'milk', 'nuts'],
    dietary: ['vegetarian', 'gluten-free'],
    modifiers: ['bread-basket'],
    pairings: ['mutabal-embers', 'lamb-chops-samr'],
    upsell: true,
    image: 'dish-hummus-ghee',
  },
  {
    slug: 'mutabal-embers',
    name: { ar: 'متبّل مدخّن على الجمر', en: 'Ember-smoked mutabal' },
    description: {
      ar: 'باذنجانٌ يُشوى في الجمر حتى تستسلم قشرته، ويُخلط بالطحينة والثوم والرمّان.',
      en: 'Aubergines blistered in the embers until the skin gives up, folded with tahini, garlic and pomegranate.',
    },
    ingredients: { ar: 'باذنجان، طحينة، ثوم، ليمون، رمّان، زيت زيتون، بقدونس', en: 'Aubergine, tahini, garlic, lemon, pomegranate, olive oil, parsley' },
    price: 32,
    calories: 310,
    allergens: ['sesame'],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['bread-basket'],
    pairings: ['hummus-ghee', 'kofta-pistachio'],
    image: 'dish-mutabal-embers',
  },
  {
    slug: 'fattoush-sumac',
    name: { ar: 'فتّوش بالسمّاق والرمّان', en: 'Fattoush, sumac & pomegranate' },
    description: {
      ar: 'أوراقٌ مقرمشة وفجلٌ وبقلةٌ وطماطم مع كسرات خبزٍ محمّص، وسمّاق ودبس رمّان.',
      en: 'Crisp leaves, radish, purslane and tomato with shards of toasted bread, sumac and pomegranate molasses.',
    },
    ingredients: {
      ar: 'خس، بقلة، فجل، طماطم، خيار، نعناع، خبز محمّص، سمّاق، دبس رمّان، زيت زيتون',
      en: 'Lettuce, purslane, radish, tomato, cucumber, mint, toasted bread, sumac, pomegranate molasses, olive oil',
    },
    price: 38,
    calories: 290,
    allergens: ['gluten'],
    dietary: ['vegan', 'dairy-free', 'nut-free'],
    pairings: ['shish-tawook', 'madhbi-chicken'],
    image: 'dish-fattoush-sumac',
  },
  {
    slug: 'tabbouleh-season',
    name: { ar: 'تبّولة الموسم', en: 'Tabbouleh of the season' },
    description: {
      ar: 'بقدونسٌ أكثر من أي شيءٍ آخر، كما ينبغي: برغلٌ ناعم ونعناعٌ وطماطم وليمونٌ وزيتٌ طيّب.',
      en: 'More parsley than anything else, as it should be: fine bulgur, mint, tomato, lemon and good oil.',
    },
    ingredients: { ar: 'بقدونس، نعناع، برغل ناعم، طماطم، بصل أخضر، ليمون، زيت زيتون', en: 'Parsley, mint, fine bulgur, tomato, spring onion, lemon, olive oil' },
    price: 36,
    calories: 240,
    allergens: ['gluten'],
    dietary: ['vegan', 'dairy-free', 'nut-free'],
    pairings: ['kofta-pistachio'],
    image: 'dish-tabbouleh-season',
  },
  {
    slug: 'sambousek',
    name: { ar: 'سمبوسك بثلاث حشوات', en: 'Sambousek, three ways' },
    description: {
      ar: 'ستّ فطائر مقرمشة: لحمٌ متبّل بالصنوبر، وجبنٌ أبيض بالنعناع، وسبانخ بالسمّاق.',
      en: 'Six crisp pastries: spiced beef and pine nuts, white cheese and mint, spinach with sumac.',
    },
    ingredients: {
      ar: 'عجينة قمح، لحم مفروم، صنوبر، جبن أبيض، نعناع، سبانخ، سمّاق، بصل',
      en: 'Wheat pastry, minced beef, pine nuts, white cheese, mint, spinach, sumac, onion',
    },
    price: 36,
    calories: 620,
    allergens: ['gluten', 'milk', 'nuts'],
    dietary: [],
    pairings: ['tamarind-lime'],
    upsell: true,
    image: 'dish-sambousek',
  },
  {
    slug: 'jareesh',
    name: { ar: 'جريش باللبن والدجاج', en: 'Jareesh with laban & slow chicken' },
    description: {
      ar: 'جريشٌ من قمح حائل يُطهى لساعاتٍ مع اللبن والدجاج، ويُختم بالبصل المقرمش وملعقةٍ من السمن.',
      en: 'Cracked wheat from Hail simmered for hours with laban and chicken, finished with crisp onions and a spoon of ghee.',
    },
    story: {
      ar: 'الطبق الذي يقيس به مطبخنا في الرياض نفسه. يُحرَّك ولا يُستعجَل؛ فالقمح هو من يقرّر متى ينضج.',
      en: 'The dish our Riyadh kitchen measures itself by. Stirred, never rushed — the wheat decides when it is ready.',
    },
    ingredients: { ar: 'جريش، لبن، دجاج، بصل، سمن، كمّون، لومي، فلفل', en: 'Cracked wheat, laban, chicken, onion, ghee, cumin, dried lime, chilli' },
    price: 64,
    calories: 690,
    spice: 1,
    allergens: ['gluten', 'milk'],
    dietary: ['nut-free'],
    modifiers: ['ghee-extra'],
    pairings: ['fattoush-sumac', 'saudi-coffee'],
    signature: true,
    image: 'dish-jareesh',
  },
  {
    slug: 'qursan',
    name: { ar: 'قرصان باللحم والخضار', en: 'Qursan of lamb & vegetables' },
    description: {
      ar: 'رقائق خبزٍ رقيق تُطوى في مرقٍ من لحم الغنم والقرع والكوسا والطماطم حتى تشربه كلّه.',
      en: 'Sheets of thin bread folded into a stew of lamb, pumpkin, courgette and tomato until they drink it all.',
    },
    ingredients: {
      ar: 'خبز قمح رقيق، لحم غنم، قرع، كوسا، باذنجان، طماطم، بصل، بهارات نجدية',
      en: 'Thin wheat bread, lamb, pumpkin, courgette, aubergine, tomato, onion, Najdi spices',
    },
    price: 78,
    calories: 820,
    spice: 1,
    allergens: ['gluten'],
    dietary: ['dairy-free', 'nut-free'],
    pairings: ['tabbouleh-season'],
    branches: ['wadi-hanifah'],
    image: 'dish-qursan',
  },
  {
    slug: 'saleeg',
    name: { ar: 'سليق طائفي', en: 'Saleeg of Taif' },
    description: {
      ar: 'أرزٌّ قصير الحبّة يُطهى على مهلٍ في مرق الدجاج والحليب حتى يصير كريميّاً، ويُقدَّم مع الدجاج المحمّر والسمن.',
      en: 'Short-grain rice cooked slowly in chicken broth and milk until creamy, served with roast chicken and ghee.',
    },
    ingredients: { ar: 'أرز قصير الحبّة، مرق دجاج، حليب، دجاج، سمن، هيل، فلفل أسود', en: 'Short-grain rice, chicken broth, milk, chicken, ghee, cardamom, black pepper' },
    price: 72,
    calories: 760,
    allergens: ['milk'],
    dietary: ['gluten-free', 'nut-free'],
    pairings: ['taif-rose-lemonade'],
    branches: ['al-balad'],
    image: 'dish-saleeg',
  },
  {
    slug: 'hassawi-kabsa',
    name: { ar: 'كبسة الرزّ الحساوي الأحمر بكتف الخروف', en: 'Red Hassawi rice kabsa, lamb shoulder' },
    description: {
      ar: 'أرزّ الأحساء الأحمر يُطهى في مرق الخروف نفسه مع اللومي وبهارات الكبسة، وكتفٌ يتفكّك فوقه.',
      en: "Al-Ahsa's red rice cooked in the lamb's own broth with loomi and kabsa spices, the shoulder falling apart on top.",
    },
    story: {
      ar: 'الرزّ الحساوي الأحمر جوزيّ النكهة وعنيد؛ يحتاج وقتاً ويردّه أضعافاً. يكفي اثنين، أو واحداً جائعاً جداً.',
      en: 'Red Hassawi rice is nutty and stubborn; it needs time and pays it back. Enough for two, or for one very hungry guest.',
    },
    ingredients: {
      ar: 'أرز حساوي أحمر، كتف خروف، بصل، طماطم، لومي، هيل، قرفة، قرنفل، لوز محمّص، زبيب',
      en: 'Red Hassawi rice, lamb shoulder, onion, tomato, dried lime, cardamom, cinnamon, cloves, toasted almonds, raisins',
    },
    price: 138,
    calories: 1450,
    spice: 1,
    allergens: ['nuts'],
    dietary: ['gluten-free', 'dairy-free'],
    modifiers: ['kabsa-extras'],
    pairings: ['fattoush-sumac', 'tamarind-lime'],
    signature: true,
    prep: 25,
    image: 'dish-hassawi-kabsa',
  },
  {
    slug: 'madhbi-chicken',
    name: { ar: 'دجاج مضبي على الحجر', en: 'Madhbi chicken on hot stones' },
    description: {
      ar: 'نصف دجاجةٍ متبّلة بالليمون والبهارات، تُطهى مفرودةً على حجارةٍ محمّاة بالنار، مع الأرزّ والدقّوس.',
      en: 'Half a chicken marinated in lime and spices, cooked flat on stones heated in the fire, with rice and daqqus.',
    },
    ingredients: {
      ar: 'دجاج، ليمون، ثوم، كمّون، كركم، أرز بسمتي، دقّوس طماطم، فلفل أخضر',
      en: 'Chicken, lime, garlic, cumin, turmeric, basmati rice, tomato daqqus, green chilli',
    },
    price: 84,
    calories: 980,
    spice: 2,
    allergens: [],
    dietary: ['gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['side-choice'],
    pairings: ['fattoush-sumac', 'hibiscus-cooler'],
    prep: 20,
    image: 'dish-madhbi-chicken',
  },
  {
    slug: 'sayadiyah',
    name: { ar: 'صيّادية الهامور', en: 'Hamour sayadiyah' },
    description: {
      ar: 'أرزٌّ مطبوخ في مرق السمك مع بصلٍ مكرمل حتى العمق، وفيليه هامور ولوزٍ محمّص.',
      en: 'Rice cooked in fish stock with deeply caramelised onions, a fillet of hamour and toasted almonds.',
    },
    ingredients: {
      ar: 'هامور، أرز، بصل مكرمل، مرق سمك، كمّون، قرفة، لوز محمّص، صلصة طحينة',
      en: 'Hamour, rice, caramelised onion, fish stock, cumin, cinnamon, toasted almonds, tahini sauce',
    },
    price: 118,
    calories: 890,
    allergens: ['fish', 'nuts', 'sesame'],
    dietary: ['gluten-free', 'dairy-free'],
    pairings: ['taif-rose-lemonade'],
    prep: 20,
    image: 'dish-sayadiyah',
  },
  {
    slug: 'mataziz',
    name: { ar: 'مطازيز بالقرع واللحم', en: 'Mataziz of pumpkin & lamb' },
    description: {
      ar: 'مربّعات عجينٍ مضغوطة باليد تُطهى في مرق لحم الغنم والقرع والكوسا، كما يستقبل نجدٌ الشتاء.',
      en: 'Hand-pressed squares of dough cooked in a stew of lamb, pumpkin and courgette — the way Najd meets winter.',
    },
    ingredients: {
      ar: 'عجينة قمح، لحم غنم، قرع، كوسا، طماطم، بصل، لومي، بهارات نجدية',
      en: 'Wheat dough, lamb, pumpkin, courgette, tomato, onion, dried lime, Najdi spices',
    },
    price: 76,
    calories: 840,
    spice: 1,
    allergens: ['gluten'],
    dietary: ['dairy-free', 'nut-free'],
    pairings: ['saudi-coffee'],
    branches: ['wadi-hanifah'],
    image: 'dish-mataziz',
  },

  // ——————————————————————————— The long shade ———————————————————————————
  {
    slug: 'gahwa-service',
    name: { ar: 'قهوة سعودية وتمر (لشخصين)', en: 'Gahwa & dates for two' },
    description: {
      ar: 'دلّة قهوةٍ سعودية بالهيل والزعفران، وأربعة فناجين، وتمرٌ من عنيزة.',
      en: 'A dallah of Saudi coffee with cardamom and saffron, four finjans, and dates from Unaizah.',
    },
    story: {
      ar: 'تُصبّ باليمين، قليلاً في كلّ مرّة. هزّ الفنجان حين تكتفي؛ هذه هي القاعدة الوحيدة.',
      en: "Poured with the right hand, a little at a time. Shake the cup when you've had enough — it is the only rule.",
    },
    ingredients: { ar: 'بن خولاني محمّص تحميصاً خفيفاً، هيل، زعفران، قرنفل، تمر', en: 'Lightly roasted Khawlani beans, cardamom, saffron, cloves, dates' },
    price: 42,
    calories: 180,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['coffee-roast'],
    pairings: ['kleija', 'luqaimat'],
    signature: true,
    image: 'dish-gahwa-service',
  },
  {
    slug: 'luqaimat',
    name: { ar: 'لقيمات بدبس التمر', en: 'Luqaimat with date syrup' },
    description: {
      ar: 'لقيماتٌ بالزعفران تُقلى عند الطلب، مقرمشةٌ من الخارج وطريّةٌ من الداخل، تحت دبس التمر والسمسم المحمّص.',
      en: 'Saffron dumplings fried to order, crisp outside and soft within, under date syrup and toasted sesame.',
    },
    ingredients: { ar: 'دقيق، خميرة، زعفران، هيل، حليب، دبس تمر، سمسم', en: 'Flour, yeast, saffron, cardamom, milk, date syrup, sesame' },
    price: 29,
    calories: 540,
    allergens: ['gluten', 'milk', 'sesame'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['saudi-coffee', 'karak-chai'],
    upsell: true,
    image: 'dish-luqaimat',
  },
  {
    slug: 'kleija',
    name: { ar: 'كليجا القصيم', en: 'Kleija of Qassim' },
    description: {
      ar: 'أقراصٌ متبّلة بالهيل واللومي ومحشوّة بعجينة التمر؛ أربعٌ في الطبق مع فنجان قهوة.',
      en: 'Round cookies spiced with cardamom and dried lime, filled with date paste — four to a plate, with a cup of gahwa.',
    },
    ingredients: { ar: 'دقيق بُرّ، سمن، عجينة تمر، هيل، لومي، شمر', en: 'Wholewheat flour, ghee, date paste, cardamom, dried lime, fennel seeds' },
    price: 26,
    calories: 460,
    allergens: ['gluten', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['gahwa-service'],
    image: 'dish-kleija',
  },
  {
    slug: 'karak-kaak',
    name: { ar: 'كرك وكعك', en: "Karak & ka'ak" },
    description: {
      ar: 'كركٌ قويّ يُغلى مع الهيل والحليب المبخّر، وحلقةُ كعكٍ بالسمسم للغمس.',
      en: "Strong karak brewed with cardamom and evaporated milk, and a ring of sesame ka'ak to dip.",
    },
    ingredients: { ar: 'شاي أسود، هيل، زعفران، حليب مبخّر، سكّر، كعك بالسمسم', en: "Black tea, cardamom, saffron, evaporated milk, sugar, sesame ka'ak" },
    price: 24,
    calories: 390,
    allergens: ['milk', 'gluten', 'sesame'],
    dietary: ['vegetarian', 'nut-free'],
    modifiers: ['sweetness'],
    image: 'dish-karak-kaak',
  },
  {
    slug: 'date-tahini-cake',
    name: { ar: 'كيكة التمر والطحينة', en: 'Date & tahini cake' },
    description: {
      ar: 'كعكةٌ داكنة رطبة من تمر السكّري تحت كراميل الطحينة ورشّة ملحٍ بحري.',
      en: 'A dark, damp cake of Sukkari dates under tahini caramel and a pinch of sea salt.',
    },
    ingredients: { ar: 'تمر سكّري، دقيق، بيض، زبدة، طحينة، سكّر، ملح بحري', en: 'Sukkari dates, flour, eggs, butter, tahini, sugar, sea salt' },
    price: 34,
    calories: 520,
    allergens: ['gluten', 'eggs', 'milk', 'sesame'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['khawlani-pour-over'],
    image: 'dish-date-tahini-cake',
  },

  // ——————————————————————————— The night courtyard ———————————————————————————
  {
    slug: 'lamb-chops-samr',
    name: { ar: 'ريش غنم على جمر السمر', en: 'Lamb chops over samr embers' },
    description: {
      ar: 'ريش غنمٍ نجدي تُشوى على جمر السمر، مع بصلٍ بالسمّاق وطماطم مشويّة وخبز.',
      en: 'Najdi lamb chops grilled over acacia embers, with sumac onions, charred tomato and flatbread.',
    },
    story: {
      ar: 'السمر يحترق ببطءٍ ونقاء؛ خشبٌ اختاره البدو لقهوتهم، ونختاره نحن للّحم.',
      en: 'Samr — desert acacia — burns slow and clean. The Bedouin chose it for their coffee; we choose it for lamb.',
    },
    ingredients: { ar: 'ريش غنم، ثوم، فلفل أسود، سمّاق، بصل، طماطم، خبز', en: 'Lamb chops, garlic, black pepper, sumac, onion, tomato, flatbread' },
    price: 168,
    calories: 980,
    allergens: ['gluten'],
    dietary: ['dairy-free', 'nut-free'],
    modifiers: ['doneness', 'side-choice'],
    pairings: ['hummus-ghee', 'pomegranate-juice'],
    signature: true,
    prep: 25,
    image: 'dish-lamb-chops-samr',
  },
  {
    slug: 'najil-salt',
    name: { ar: 'نجل مخبوز بالملح (لشخصين)', en: 'Whole najil baked in salt, for two' },
    description: {
      ar: 'نجل اليوم من سوق جدّة، يُغلَّف بقشرةٍ من الملح والأعشاب، وتُكسَر أمامك على الطاولة.',
      en: "The day's coral grouper from the Jeddah market, sealed in a crust of salt and herbs and cracked open at the table.",
    },
    story: {
      ar: 'الملح يحبس السمكة في بخارها. وصوت انكسار القشرة أعلى ما يُسمع في الفناء عند التاسعة.',
      en: 'Salt keeps the fish in its own steam. The crack of the crust is the loudest sound in the courtyard at nine.',
    },
    ingredients: {
      ar: 'سمك نجل كامل، ملح بحري، بياض بيض، شبت، ليمون، ورق غار، زيت زيتون',
      en: 'Whole najil (coral grouper), sea salt, egg white, dill, lemon, bay leaf, olive oil',
    },
    price: 240,
    calories: 900,
    allergens: ['fish', 'eggs'],
    dietary: ['gluten-free', 'dairy-free', 'nut-free'],
    pairings: ['tabbouleh-season', 'taif-rose-lemonade'],
    signature: true,
    prep: 35,
    branches: ['al-balad'],
    image: 'dish-najil-salt',
  },
  {
    slug: 'prawns-loomi',
    name: { ar: 'روبيان البحر الأحمر بزبدة اللومي', en: 'Red Sea prawns, loomi butter' },
    description: {
      ar: 'روبيانٌ كبير يُشوى بقشره ويُدهن بزبدة اللومي الأسود والثوم والكزبرة.',
      en: 'Large prawns grilled in the shell and basted with butter, black loomi, garlic and coriander.',
    },
    ingredients: { ar: 'روبيان البحر الأحمر، زبدة، لومي، ثوم، كزبرة، فلفل، ليمون', en: 'Red Sea prawns, butter, dried lime, garlic, coriander, chilli, lemon' },
    price: 128,
    calories: 520,
    spice: 1,
    allergens: ['crustaceans', 'milk'],
    dietary: ['gluten-free', 'nut-free'],
    pairings: ['fattoush-sumac'],
    image: 'dish-prawns-loomi',
  },
  {
    slug: 'octopus-tahini',
    name: { ar: 'أخطبوط مشوي بطحينة مدخّنة', en: 'Charred octopus, smoked tahini' },
    description: {
      ar: 'أخطبوطٌ يُطهى حتى يلين ثم يُحمَّر على الجمر، فوق طحينةٍ مدخّنة مع بصلٍ مخلّل وزيت البقدونس.',
      en: 'Octopus braised until tender, then charred over embers, on smoked tahini with pickled onion and parsley oil.',
    },
    ingredients: {
      ar: 'أخطبوط، طحينة، ليمون، ثوم، بصل مخلّل، بقدونس، زيت زيتون، فلفل حلبي',
      en: 'Octopus, tahini, lemon, garlic, pickled onion, parsley, olive oil, Aleppo pepper',
    },
    price: 118,
    calories: 460,
    spice: 1,
    allergens: ['molluscs', 'sesame'],
    dietary: ['gluten-free', 'dairy-free', 'nut-free'],
    pairings: ['warak-enab'],
    image: 'dish-octopus-tahini',
  },
  {
    slug: 'lamb-mandi',
    name: { ar: 'مندي كتف الخروف', en: 'Lamb shoulder mandi' },
    description: {
      ar: 'كتف خروفٍ يُطهى خمس ساعاتٍ فوق الأرزّ في حفرةٍ محكمة الإغلاق، مدخّناً وطريّاً، مع صلصة طماطم حادّة.',
      en: 'A lamb shoulder cooked for five hours above rice in a sealed pit, smoky and soft, with a sharp tomato salsa.',
    },
    ingredients: {
      ar: 'كتف خروف، أرز بسمتي، بهارات المندي، لومي، بصل، زبيب، لوز، صلصة طماطم',
      en: 'Lamb shoulder, basmati rice, mandi spices, dried lime, onion, raisins, almonds, tomato salsa',
    },
    price: 188,
    calories: 1600,
    spice: 1,
    allergens: ['nuts'],
    dietary: ['gluten-free', 'dairy-free'],
    pairings: ['fattoush-sumac', 'hibiscus-cooler'],
    prep: 20,
    image: 'dish-lamb-mandi',
  },
  {
    slug: 'shish-tawook',
    name: { ar: 'شيش طاووق وثوم', en: 'Shish tawook, toum' },
    description: {
      ar: 'أفخاذ دجاجٍ متبّلة باللبن والليمون والبابريكا، تُشوى على الأسياخ وتُقدَّم مع الثوم المخفوق.',
      en: 'Chicken thighs marinated in yoghurt, lemon and paprika, grilled on skewers and served with whipped garlic toum.',
    },
    ingredients: {
      ar: 'أفخاذ دجاج، لبن زبادي، ليمون، بابريكا، ثوم، زيت زيتون، مخلّل، خبز',
      en: 'Chicken thighs, yoghurt, lemon, paprika, garlic, olive oil, pickles, flatbread',
    },
    price: 74,
    calories: 780,
    allergens: ['milk', 'gluten'],
    dietary: ['nut-free'],
    modifiers: ['side-choice'],
    pairings: ['fattoush-sumac', 'mutabal-embers'],
    image: 'dish-shish-tawook',
  },
  {
    slug: 'kofta-pistachio',
    name: { ar: 'كفتة لحم بالفستق', en: 'Lamb & pistachio kofta' },
    description: {
      ar: 'لحم غنمٍ مفروم باليد مع الفستق والبقدونس والبهارات السبع، يُشوى على الجمر فوق طبقةٍ من الطحينة.',
      en: 'Hand-chopped lamb with pistachio, parsley and seven spices, grilled over embers on a smear of tahini.',
    },
    ingredients: {
      ar: 'لحم غنم، فستق حلبي، بصل، بقدونس، بهارات سبعة، طحينة، بصل بالسمّاق',
      en: 'Lamb, pistachio, onion, parsley, seven spices, tahini, sumac onion',
    },
    price: 86,
    calories: 820,
    allergens: ['nuts', 'sesame'],
    dietary: ['gluten-free', 'dairy-free'],
    pairings: ['tabbouleh-season', 'mutabal-embers'],
    image: 'dish-kofta-pistachio',
  },
  {
    slug: 'cauliflower-tahini',
    name: { ar: 'قرنبيط مشوي بالطحينة ودبس الرمّان', en: 'Roasted cauliflower, tahini, pomegranate' },
    description: {
      ar: 'زهرة قرنبيطٍ كاملة تُشوى حتى تتحمّص أطرافها، فوق الطحينة مع دبس الرمّان والأعشاب والبذور.',
      en: 'A whole cauliflower roasted until the edges catch, over tahini, with pomegranate molasses, herbs and seeds.',
    },
    ingredients: {
      ar: 'قرنبيط، طحينة، ليمون، دبس رمّان، رمّان، نعناع، بقدونس، بذور القرع',
      en: 'Cauliflower, tahini, lemon, pomegranate molasses, pomegranate, mint, parsley, pumpkin seeds',
    },
    price: 48,
    calories: 380,
    allergens: ['sesame'],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    pairings: ['warak-enab', 'hibiscus-cooler'],
    image: 'dish-cauliflower-tahini',
  },
  {
    slug: 'warak-enab',
    name: { ar: 'ورق عنب بدبس الرمّان', en: 'Vine leaves, pomegranate molasses' },
    description: {
      ar: 'ورق عنبٍ ملفوفٌ بإحكامٍ على الأرزّ والطماطم والأعشاب، يُطهى على مهلٍ بالليمون ودبس الرمّان.',
      en: 'Vine leaves rolled tight around rice, tomato and herbs, cooked slowly in lemon and pomegranate molasses.',
    },
    ingredients: {
      ar: 'ورق عنب، أرز، طماطم، بقدونس، نعناع، بصل، ليمون، دبس رمّان، زيت زيتون',
      en: 'Vine leaves, rice, tomato, parsley, mint, onion, lemon, pomegranate molasses, olive oil',
    },
    price: 42,
    calories: 330,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    pairings: ['muhammara'],
    image: 'dish-warak-enab',
  },
  {
    slug: 'aubergine-fatteh',
    name: { ar: 'فتّة الباذنجان المشوي', en: 'Charred aubergine fatteh' },
    description: {
      ar: 'طبقاتٌ من الخبز المقرمش والباذنجان المشوي والحمّص تحت لبنٍ بالثوم، وصنوبرٌ في سمنٍ حار.',
      en: 'Layers of crisp bread, charred aubergine and chickpeas under garlic yoghurt, with pine nuts in hot ghee.',
    },
    ingredients: {
      ar: 'باذنجان، حمّص، خبز مقرمش، لبن، ثوم، طحينة، صنوبر، سمن، رمّان',
      en: 'Aubergine, chickpeas, crisp bread, yoghurt, garlic, tahini, pine nuts, ghee, pomegranate',
    },
    price: 54,
    calories: 640,
    allergens: ['gluten', 'milk', 'nuts', 'sesame'],
    dietary: ['vegetarian'],
    pairings: ['kofta-pistachio'],
    image: 'dish-aubergine-fatteh',
  },
  {
    slug: 'muhammara',
    name: { ar: 'محمّرة', en: 'Muhammara' },
    description: {
      ar: 'فلفلٌ أحمر مشويّ يُدقّ مع الجوز ودبس الرمّان وشيءٍ من الحرارة.',
      en: 'Roasted red peppers pounded with walnuts, pomegranate molasses and a little heat.',
    },
    ingredients: {
      ar: 'فلفل أحمر، جوز، فتات خبز، دبس رمّان، كمّون، فلفل حلبي، زيت زيتون',
      en: 'Red pepper, walnuts, breadcrumbs, pomegranate molasses, cumin, Aleppo pepper, olive oil',
    },
    price: 34,
    calories: 360,
    spice: 2,
    allergens: ['nuts', 'gluten'],
    dietary: ['vegan', 'dairy-free'],
    modifiers: ['bread-basket'],
    pairings: ['warak-enab', 'hummus-ghee'],
    image: 'dish-muhammara',
  },
  {
    slug: 'halloumi-dates',
    name: { ar: 'حلّوم مشوي بالتمر وعسل الزعتر', en: 'Grilled halloumi, dates & thyme honey' },
    description: {
      ar: 'شرائح حلّومٍ سميكة تُحمَّر على الصاج، مع رُطَبٍ طازجٍ وعسل الزعتر وسمسمٍ محمّص.',
      en: 'Thick slices of halloumi seared on the plancha, with fresh rutab, thyme honey and toasted sesame.',
    },
    ingredients: { ar: 'حلّوم، رطب، عسل الزعتر، سمسم، زيت زيتون، قشر ليمون', en: 'Halloumi, rutab, thyme honey, sesame, olive oil, lemon zest' },
    price: 52,
    calories: 480,
    allergens: ['milk', 'sesame'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    pairings: ['pomegranate-juice'],
    image: 'dish-halloumi-dates',
  },
  {
    slug: 'harees-lamb',
    name: { ar: 'هريس باللحم', en: 'Harees with slow lamb' },
    description: {
      ar: 'قمحٌ ولحمٌ يُضربان معاً بعد ليلةٍ على النار حتى ينعما، مع السمن والقرفة ورشّة ملح.',
      en: 'Wheat and lamb beaten together after a night on the fire until smooth, with ghee, cinnamon and a pinch of salt.',
    },
    ingredients: { ar: 'قمح، لحم غنم، سمن، قرفة، هيل، ملح', en: 'Wheat, lamb, ghee, cinnamon, cardamom, salt' },
    price: 74,
    calories: 760,
    allergens: ['gluten', 'milk'],
    dietary: ['nut-free'],
    pairings: ['saudi-coffee'],
    image: 'dish-harees-lamb',
  },
  {
    slug: 'samak-harra',
    name: { ar: 'سمك حرّة', en: 'Samak harra' },
    description: {
      ar: 'فيليه سمك اليوم يُخبز في صلصةٍ حارّة من الطحينة والكزبرة والفلفل والليمون، ويُختم بالجوز المحمّص.',
      en: "The day's fish fillet baked in a hot sauce of tahini, coriander, chilli and lemon, finished with toasted walnuts.",
    },
    ingredients: {
      ar: 'فيليه سمك أبيض، طحينة، كزبرة، ثوم، فلفل أحمر حار، ليمون، جوز، زيت زيتون',
      en: 'White fish fillet, tahini, coriander, garlic, hot red chilli, lemon, walnuts, olive oil',
    },
    price: 112,
    calories: 620,
    spice: 3,
    allergens: ['fish', 'sesame', 'nuts'],
    dietary: ['gluten-free', 'dairy-free'],
    pairings: ['tabbouleh-season'],
    image: 'dish-samak-harra',
  },

  // ——————————————————————————— Sweets ———————————————————————————
  {
    slug: 'kunafa-nabulsi',
    name: { ar: 'كنافة بالجبنة النابلسية', en: 'Kunafa with Nabulsi cheese' },
    description: {
      ar: 'عجينة كنافةٍ وجبنةٌ نابلسية مطّاطة تُخبز في صينيةٍ نحاسية، وتُسقى بقطر ماء الزهر، ويعلوها الفستق.',
      en: 'Shredded pastry and stretchy Nabulsi cheese baked in a copper tray, soaked in orange-blossom syrup, pistachio on top.',
    },
    ingredients: { ar: 'عجينة كنافة، جبنة نابلسية، سمن، قطر، ماء زهر، فستق حلبي', en: 'Kataifi pastry, Nabulsi cheese, ghee, sugar syrup, orange blossom water, pistachio' },
    price: 48,
    calories: 690,
    allergens: ['gluten', 'milk', 'nuts'],
    dietary: ['vegetarian'],
    pairings: ['saudi-coffee', 'mint-tea'],
    signature: true,
    image: 'dish-kunafa-nabulsi',
  },
  {
    slug: 'umm-ali',
    name: { ar: 'أمّ علي', en: 'Umm Ali' },
    description: {
      ar: 'رقائق عجينٍ مخبوزة تتشرّب الحليب الدافئ المتبّل مع المكسّرات والزبيب، ويتحمّص وجهها تحت النار.',
      en: 'Baked pastry soaked in warm spiced milk with nuts and raisins, its top blistered under the grill.',
    },
    ingredients: {
      ar: 'عجينة منفوخة، حليب، قشطة، سكّر، هيل، لوز، فستق، جوز هند، زبيب',
      en: 'Puff pastry, milk, cream, sugar, cardamom, almonds, pistachio, coconut, raisins',
    },
    price: 42,
    calories: 740,
    allergens: ['gluten', 'milk', 'nuts'],
    dietary: ['vegetarian'],
    pairings: ['mint-tea'],
    image: 'dish-umm-ali',
  },
  {
    slug: 'muhallabia-rose',
    name: { ar: 'مهلّبية بالورد والفستق', en: 'Muhallabia, rose & pistachio' },
    description: {
      ar: 'مهلّبيةٌ بالحليب يلامسها ماء الورد الطائفي، تحت مربّى بتلات الورد والفستق المطحون.',
      en: 'Milk pudding with a whisper of Taif rose water, under rose-petal jam and ground pistachio.',
    },
    ingredients: { ar: 'حليب، طحين أرز، سكّر، ماء ورد طائفي، مربّى الورد، فستق', en: 'Milk, rice flour, sugar, Taif rose water, rose-petal jam, pistachio' },
    price: 34,
    calories: 380,
    allergens: ['milk', 'nuts'],
    dietary: ['vegetarian', 'gluten-free'],
    pairings: ['khawlani-pour-over'],
    image: 'dish-muhallabia-rose',
  },
  {
    slug: 'saffron-ice-cream',
    name: { ar: 'آيس كريم الزعفران والهيل', en: 'Saffron & cardamom ice cream' },
    description: {
      ar: 'يُخفق كلّ عصر: زعفرانٌ وهيلٌ وشيءٌ من المستكة، مع فُتات الكليجا.',
      en: 'Churned every afternoon: saffron, cardamom and a little mastic, with crumbled kleija.',
    },
    ingredients: { ar: 'حليب، قشطة، بيض، سكّر، زعفران، هيل، مستكة، فتات كليجا', en: 'Milk, cream, eggs, sugar, saffron, cardamom, mastic, kleija crumbs' },
    price: 32,
    calories: 410,
    allergens: ['milk', 'eggs', 'gluten'],
    dietary: ['vegetarian', 'nut-free'],
    pairings: ['date-tahini-cake'],
    upsell: true,
    image: 'dish-saffron-ice-cream',
  },
  {
    slug: 'basbousa-cream',
    name: { ar: 'بسبوسة بالقشطة', en: 'Basbousa with clotted cream' },
    description: {
      ar: 'كعكة سميدٍ تُسقى بالقطر وهي ساخنة، وتُشقّ وتُحشى بالقشطة، وعلى كلّ مربّعٍ لوزة.',
      en: 'Semolina cake soaked in syrup while hot, split and filled with clotted cream, an almond on every square.',
    },
    ingredients: { ar: 'سميد، لبن زبادي، سكّر، جوز هند، سمن، قشطة، لوز، قطر', en: 'Semolina, yoghurt, sugar, coconut, ghee, clotted cream, almonds, syrup' },
    price: 36,
    calories: 560,
    allergens: ['gluten', 'milk', 'nuts'],
    dietary: ['vegetarian'],
    pairings: ['karak-chai'],
    image: 'dish-basbousa-cream',
  },

  // ——————————————————————————— Coffee, tea & coolers ———————————————————————————
  {
    slug: 'saudi-coffee',
    name: { ar: 'قهوة سعودية', en: 'Saudi coffee' },
    description: {
      ar: 'تحميصٌ خفيف لبنٍّ خولاني مع الهيل وخيطٍ من الزعفران، يُصبّ بالفنجان.',
      en: 'A light roast of Khawlani beans with cardamom and a thread of saffron, poured by the finjan.',
    },
    price: 18,
    calories: 10,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['coffee-roast'],
    pairings: ['kleija', 'dates-laban'],
    image: 'dish-saudi-coffee',
  },
  {
    slug: 'khawlani-pour-over',
    name: { ar: 'قهوة خولانية مقطّرة', en: 'Khawlani pour-over' },
    description: {
      ar: 'بنٌّ خولاني من مدرّجٍ واحد في جبال جازان، يُقطَّر يدوياً: فاكهةٌ ذات نواة وعسلٌ ونهايةٌ جافّة.',
      en: 'Single-terrace Khawlani from the Jazan mountains, brewed by hand: stone fruit, honey, a dry finish.',
    },
    story: {
      ar: 'يُزرع البنّ على هذه المدرّجات منذ قرون. نشتري من ثلاث عائلات ونحمّص كلّ أحد.',
      en: 'Coffee has grown on these terraces for centuries. We buy from three families and roast every Sunday.',
    },
    price: 32,
    calories: 5,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    pairings: ['date-tahini-cake', 'areeka'],
    signature: true,
    image: 'dish-khawlani-pour-over',
  },
  {
    slug: 'karak-chai',
    name: { ar: 'شاي كرك', en: 'Karak chai' },
    description: {
      ar: 'شايٌ أسود يُغلى بقوّةٍ مع الهيل والزعفران والحليب المبخّر؛ حلوٌ وقويٌّ وساخنٌ جداً.',
      en: 'Black tea boiled hard with cardamom, saffron and evaporated milk — sweet, strong and very hot.',
    },
    price: 16,
    calories: 190,
    allergens: ['milk'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    modifiers: ['sweetness'],
    pairings: ['mutabbaq', 'luqaimat'],
    image: 'dish-karak-chai',
  },
  {
    slug: 'mint-tea',
    name: { ar: 'شاي بالنعناع', en: 'Mint tea' },
    description: { ar: 'شايٌ أخضر ونعناعٌ طازج في كوبٍ صغير، يُحلّى على ذوقك.', en: 'Green tea and fresh mint in a small glass, sweetened to your taste.' },
    price: 14,
    calories: 40,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['sweetness'],
    pairings: ['kunafa-nabulsi'],
    image: 'dish-mint-tea',
  },
  {
    slug: 'hibiscus-cooler',
    name: { ar: 'كركديه مثلّج', en: 'Hibiscus cooler' },
    description: {
      ar: 'كركديه يُنقع بارداً طوال الليل مع قليلٍ من الزنجبيل والليم، على الثلج.',
      en: 'Hibiscus steeped cold overnight with a little ginger and lime, over ice.',
    },
    price: 22,
    calories: 90,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['cooler-size'],
    upsell: true,
    image: 'dish-hibiscus-cooler',
  },
  {
    slug: 'tamarind-lime',
    name: { ar: 'تمر هندي بالليمون', en: 'Tamarind & lime' },
    description: {
      ar: 'تمرٌ هندي معصورٌ ومحلّى مع عصرة ليمون، بلون الجدار في آخر العصر.',
      en: 'Tamarind pressed and sweetened with a squeeze of lime — the colour of the wall at the end of the afternoon.',
    },
    price: 22,
    calories: 150,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['cooler-size'],
    image: 'dish-tamarind-lime',
  },
  {
    slug: 'sobia',
    name: { ar: 'سوبيا', en: 'Sobia' },
    description: {
      ar: 'مشروب جدّة القديم في رمضان والصيف: شعيرٌ وخبزٌ منقوعان طوال الليل مع الهيل والقرفة، يُقدَّم بارداً جداً.',
      en: "Jeddah's old Ramadan and summer drink: barley and bread soaked overnight with cardamom and cinnamon, served ice-cold.",
    },
    price: 20,
    calories: 180,
    allergens: ['gluten'],
    dietary: ['vegan', 'dairy-free', 'nut-free'],
    modifiers: ['cooler-size'],
    branches: ['al-balad'],
    image: 'dish-sobia',
  },
  {
    slug: 'date-laban-shake',
    name: { ar: 'مخفوق التمر واللبن', en: 'Date & laban shake' },
    description: { ar: 'تمرٌ سكّري يُخفق مع اللبن البارد ورشّة هيل؛ فطورٌ في كوب.', en: 'Sukkari dates blended with cold laban and a pinch of cardamom. Breakfast in a glass.' },
    price: 28,
    calories: 320,
    allergens: ['milk'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    upsell: true,
    image: 'dish-date-laban-shake',
  },
  {
    slug: 'taif-rose-lemonade',
    name: { ar: 'ليموناضة الورد الطائفي', en: 'Taif rose lemonade' },
    description: { ar: 'ليمونٌ طازج وماءُ وردٍ طائفي وقليلٌ من السكّر، يُرجّ على الثلج.', en: 'Fresh lemon, Taif rose water and a little sugar, shaken over ice.' },
    price: 24,
    calories: 120,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    modifiers: ['cooler-size'],
    upsell: true,
    image: 'dish-taif-rose-lemonade',
  },
  {
    slug: 'pomegranate-juice',
    name: { ar: 'عصير رمّان', en: 'Pomegranate, pressed' },
    description: { ar: 'يُعصر عند الطلب من رمّان الموسم، بلا إضافات.', en: "Pressed to order from the season's pomegranates. Nothing added." },
    price: 26,
    calories: 160,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    image: 'dish-pomegranate-juice',
  },

  // ——————————————————————————— Small shade ———————————————————————————
  {
    slug: 'little-shish',
    name: { ar: 'شيش صغير مع الرز', en: 'Little shish with rice' },
    description: { ar: 'سيخان من الدجاج الخفيف مع أرزٍّ بالزعفران وأصابع خيار.', en: 'Two skewers of mild chicken with saffron rice and cucumber sticks.' },
    price: 38,
    calories: 520,
    allergens: ['milk'],
    dietary: ['gluten-free', 'nut-free'],
    tags: ['kids'],
    image: 'dish-little-shish',
  },
  {
    slug: 'manakish-bites',
    name: { ar: 'مناقيش جبنة صغيرة', en: 'Cheese manakish bites' },
    description: { ar: 'ثلاث مناقيش صغيرة بالجبنة الذائبة، مقطّعةٌ لتناسب الأيدي الصغيرة.', en: 'Three little flatbreads with melted cheese, cut for small hands.' },
    price: 22,
    calories: 430,
    allergens: ['gluten', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    tags: ['kids'],
    image: 'dish-manakish-bites',
  },
  {
    slug: 'kofta-sliders',
    name: { ar: 'ساندويتشات كفتة صغيرة', en: 'Kofta sliders' },
    description: { ar: 'خبزتان طريّتان بكفتة لحمٍ خفيفة وطماطم وقليلٍ من الطحينة.', en: 'Two soft buns with mild lamb kofta, tomato and a little tahini.' },
    price: 34,
    calories: 560,
    allergens: ['gluten', 'sesame'],
    dietary: ['dairy-free', 'nut-free'],
    tags: ['kids'],
    image: 'dish-kofta-sliders',
  },
  {
    slug: 'fruit-cup',
    name: { ar: 'كوب فاكهة ولبن', en: 'Fruit cup & laban' },
    description: { ar: 'فاكهة الموسم في كوبٍ مع لبنٍ محلّى ورشّة دبس تمر.', en: "The season's fruit in a cup with sweet laban and a drizzle of date syrup." },
    price: 18,
    calories: 210,
    allergens: ['milk'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    tags: ['kids'],
    image: 'dish-fruit-cup',
  },

  // ——————————————————————————— The Sundial (tasting courses) ———————————————————————————
  {
    slug: 'sundial-dawn',
    name: { ar: 'الفجر: تمرٌ وقهوةٌ وقشطة', en: 'Dawn: date, coffee, cream' },
    description: { ar: 'رُطَبةٌ واحدة محشوّة بقشطة القهوة، ورشفةٌ من أول صبّة.', en: 'A single rutab filled with coffee cream, and a sip of the first pour.' },
    price: 0,
    allergens: ['milk'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    orderable: false,
    image: 'dish-sundial-dawn',
  },
  {
    slug: 'sundial-morning',
    name: { ar: 'الضحى: خبز التنّور وسمنٌ وعسل', en: 'Morning: tannour bread, ghee, honey' },
    description: { ar: 'خبزٌ من أول خبزةٍ لأبي صالح مع سمنٍ مخمّر وعسل السدر.', en: "Bread from Abu Saleh's first batch with cultured ghee and sidr honey." },
    price: 0,
    allergens: ['gluten', 'milk'],
    dietary: ['vegetarian', 'nut-free'],
    orderable: false,
    image: 'dish-sundial-morning',
  },
  {
    slug: 'sundial-noon',
    name: { ar: 'الظهيرة: سمكٌ نيء وليمٌ وفلفلٌ أخضر', en: 'Noon: raw fish, lime, green chilli' },
    description: {
      ar: 'صيد الصباح مقطّعاً نيئاً، يُتبّل بالليم والفلفل الأخضر وزيت الزيتون البارد.',
      en: "The morning's catch, sliced raw and dressed with lime, green chilli and cold olive oil.",
    },
    price: 0,
    spice: 1,
    allergens: ['fish'],
    dietary: ['gluten-free', 'dairy-free', 'nut-free'],
    orderable: false,
    image: 'dish-sundial-noon',
  },
  {
    slug: 'sundial-long-shade',
    name: { ar: 'الظلّ الطويل: رزٌّ بالزعفران ولبنٌ مدخّن', en: 'The long shade: saffron rice, smoked laban' },
    description: { ar: 'رزٌّ حساويّ أحمر بالزعفران، وملعقةُ لبنٍ مدخّنٍ على السمر.', en: 'Red Hassawi rice with saffron and a spoon of laban smoked over samr.' },
    price: 0,
    allergens: ['milk'],
    dietary: ['vegetarian', 'gluten-free', 'nut-free'],
    orderable: false,
    image: 'dish-sundial-long-shade',
  },
  {
    slug: 'sundial-maghrib',
    name: { ar: 'المغرب: لحمٌ ولوميٌّ وجمر', en: 'Maghrib: lamb, loomi, embers' },
    description: { ar: 'متن لحمٍ يُطهى على الجمر مع غياب الشمس، مع اللومي والبصل المشوي.', en: 'Lamb loin cooked on the embers as the sun goes, with loomi and charred onion.' },
    price: 0,
    allergens: [],
    dietary: ['gluten-free', 'dairy-free', 'nut-free'],
    orderable: false,
    image: 'dish-sundial-maghrib',
  },
  {
    slug: 'sundial-night',
    name: { ar: 'الليل: وردٌ وفستقٌ وقشطة', en: 'Night: rose, pistachio, cream' },
    description: { ar: 'وردٌ طائفي وفستقٌ وقشطة؛ الفناء بعد أن تُضاء القناديل.', en: 'Taif rose, pistachio and cream — the courtyard after the lamps are lit.' },
    price: 0,
    allergens: ['milk', 'nuts'],
    dietary: ['vegetarian', 'gluten-free'],
    orderable: false,
    image: 'dish-sundial-night',
  },
  {
    slug: 'sundial-midnight',
    name: { ar: 'منتصف الليل: شايٌ بالنعناع وتمرة', en: 'Midnight: mint tea and one date' },
    description: { ar: 'كوب شايٍ بالنعناع وتمرةٌ واحدةٌ كاملة، لطريق العودة.', en: 'A glass of mint tea and one perfect date, for the walk home.' },
    price: 0,
    allergens: [],
    dietary: ['vegan', 'gluten-free', 'dairy-free', 'nut-free'],
    orderable: false,
    image: 'dish-sundial-midnight',
  },
];

export const menus: SeedMenu[] = [
  {
    slug: 'morning',
    kind: 'breakfast',
    name: { ar: 'ظلّ الصباح', en: 'Morning shade' },
    hour: { ar: 'الفطور', en: 'Breakfast' },
    description: {
      ar: 'خبزٌ من التنّور، وبيضٌ من المقلاة، وقهوةٌ عند الجدار الشرقي والفناء ما زال بارداً.',
      en: 'Bread from the tannour, eggs from the pan, coffee by the east wall while the courtyard is still cool.',
    },
    schedule: [
      { weekdays: [0, 1, 2, 3, 4, 6], start: '07:00', end: '11:30' },
      { weekdays: [5], start: '08:00', end: '12:30' },
    ],
    image: 'place-courtyard-sun',
    categories: [
      { slug: 'tannour', name: { ar: 'من التنّور', en: 'From the tannour' }, items: ['akkawi-manakish', 'labneh-zaatar', 'mutabbaq'] },
      { slug: 'pot-and-pan', name: { ar: 'من القِدر والمقلاة', en: 'From the pot and the pan' }, items: ['tamees-foul', 'shakshuka-loomi', 'eggs-east-wall', 'balaleet'] },
      { slug: 'sweet-mornings', name: { ar: 'حلوُ الصباح', en: 'Sweet mornings' }, items: ['areeka', 'masoub', 'dates-laban'] },
      { slug: 'morning-cups', name: { ar: 'فناجين الصباح', en: 'Morning cups' }, items: ['saudi-coffee', 'karak-chai', 'khawlani-pour-over', 'date-laban-shake'] },
    ],
  },
  {
    slug: 'noon',
    kind: 'lunch',
    name: { ar: 'الظلّ القصير', en: 'The short shade' },
    hour: { ar: 'الغداء', en: 'Lunch' },
    description: {
      ar: 'عند الظهيرة يقصر الظلّ ويطول الغداء: قدورٌ من المطبخ النجدي، وسمكٌ من سوق الصباح، وخبزٌ ما زال دافئاً.',
      en: 'At noon the shade is shortest and lunch is longest: pots from the Najdi kitchen, fish from the morning market, bread still warm.',
    },
    schedule: [{ weekdays: EVERY_DAY, start: '12:30', end: '16:00' }],
    image: 'place-lattice-light',
    categories: [
      { slug: 'to-share', name: { ar: 'للمشاركة', en: 'To share' }, items: ['hummus-ghee', 'mutabal-embers', 'fattoush-sumac', 'tabbouleh-season', 'sambousek'] },
      { slug: 'pots', name: { ar: 'قدور البيت', en: 'Pots of the house' }, items: ['jareesh', 'saleeg', 'qursan', 'mataziz', 'hassawi-kabsa'] },
      { slug: 'sea-and-stone', name: { ar: 'من البحر والحجر', en: 'From the sea and the stone' }, items: ['madhbi-chicken', 'sayadiyah'] },
    ],
  },
  {
    slug: 'afternoon',
    kind: 'afternoon',
    name: { ar: 'الظلّ الطويل', en: 'The long shade' },
    hour: { ar: 'القهوة والحلو', en: 'Coffee & sweets' },
    description: {
      ar: 'حين يمتدّ الظلّ على الفناء: قهوةٌ تُصبّ من الدلّة، وشيءٌ حلو، ولا موعد ينتظرك.',
      en: 'When the shade stretches across the courtyard: coffee poured from the dallah, something sweet, and nowhere to be.',
    },
    schedule: [{ weekdays: EVERY_DAY, start: '16:00', end: '18:30' }],
    image: 'place-palm-shadow-1',
    categories: [
      { slug: 'coffee', name: { ar: 'القهوة', en: 'Coffee' }, items: ['gahwa-service', 'khawlani-pour-over', 'karak-kaak'] },
      { slug: 'afternoon-sweets', name: { ar: 'حلوى العصر', en: 'Afternoon sweets' }, items: ['luqaimat', 'kleija', 'date-tahini-cake', 'kunafa-nabulsi'] },
    ],
  },
  {
    slug: 'night',
    kind: 'dinner',
    name: { ar: 'فناء الليل', en: 'The night courtyard' },
    hour: { ar: 'العشاء', en: 'Dinner' },
    description: {
      ar: 'بعد المغرب يصير الظلّ السماءَ كلّها. جمرٌ وقناديل، وبحرٌ ومشوى؛ عشاءٌ تحت سقف الفناء نفسه.',
      en: "After maghrib the shade becomes the whole sky. Embers, lamps, the sea and the grill — dinner under the courtyard's own ceiling.",
    },
    schedule: [
      { weekdays: [0, 1, 2, 3, 6], start: '19:00', end: '00:30' },
      { weekdays: [4, 5], start: '19:00', end: '01:30' },
    ],
    image: 'place-night-courtyard',
    categories: [
      { slug: 'to-begin', name: { ar: 'للبداية', en: 'To begin' }, items: ['hummus-ghee', 'mutabal-embers', 'warak-enab', 'muhammara', 'halloumi-dates', 'cauliflower-tahini', 'aubergine-fatteh'] },
      { slug: 'embers', name: { ar: 'على الجمر', en: 'Over the embers' }, items: ['lamb-chops-samr', 'kofta-pistachio', 'shish-tawook'] },
      { slug: 'sea', name: { ar: 'من البحر', en: 'From the sea' }, items: ['najil-salt', 'prawns-loomi', 'octopus-tahini', 'samak-harra'] },
      { slug: 'pot', name: { ar: 'من القِدر', en: 'From the pot' }, items: ['lamb-mandi', 'hassawi-kabsa', 'harees-lamb'] },
    ],
  },
  {
    slug: 'sundial',
    kind: 'tasting',
    name: { ar: 'المزولة', en: 'The Sundial' },
    hour: { ar: 'قائمة التذوّق', en: 'Tasting menu' },
    description: {
      ar: 'سبعة أطباق، لكلّ ساعةٍ من يومنا طبق، من أول الضوء حتى منتصف الليل. تُقدَّم على طاولة الفناء، بالحجز المسبق.',
      en: 'Seven courses, one for each hour of our day, from first light to midnight. Served at the courtyard table, by reservation.',
    },
    schedule: [{ weekdays: [3, 4, 5, 6], start: '19:30', end: '22:00' }],
    isTasting: true,
    tastingPrice: 485,
    image: 'place-candle-table',
    categories: [
      {
        slug: 'courses',
        name: { ar: 'سبع ساعات', en: 'Seven hours' },
        items: ['sundial-dawn', 'sundial-morning', 'sundial-noon', 'sundial-long-shade', 'sundial-maghrib', 'sundial-night', 'sundial-midnight'],
      },
    ],
  },
  {
    slug: 'sweets',
    kind: 'desserts',
    name: { ar: 'الحلو', en: 'Sweets' },
    hour: { ar: 'من الظهيرة', en: 'From noon' },
    description: { ar: 'الحلو من الظهيرة حتى تُطفأ القناديل.', en: 'Sweet things from noon until the lamps go out.' },
    schedule: [
      { weekdays: [0, 1, 2, 3, 6], start: '12:30', end: '00:30' },
      { weekdays: [4, 5], start: '12:30', end: '01:30' },
    ],
    image: 'ing-honey',
    categories: [
      { slug: 'sweets', name: { ar: 'الحلو', en: 'Sweets' }, items: ['kunafa-nabulsi', 'umm-ali', 'muhallabia-rose', 'saffron-ice-cream', 'basbousa-cream', 'date-tahini-cake', 'luqaimat'] },
    ],
  },
  {
    slug: 'cups',
    kind: 'drinks',
    name: { ar: 'القهوة والشاي والمبرّدات', en: 'Coffee, tea & coolers' },
    hour: { ar: 'طوال اليوم', en: 'All day' },
    description: {
      ar: 'قهوةٌ من جازان، وشايٌ من إبريقٍ لا يبرد، ومبرّداتٌ من صيف الحجاز القديم.',
      en: 'Coffee from Jazan, tea from a kettle that never cools, and coolers from the old Hijazi summer.',
    },
    schedule: [],
    image: 'craft-coffee-pour',
    categories: [
      { slug: 'coffee', name: { ar: 'القهوة', en: 'Coffee' }, items: ['saudi-coffee', 'khawlani-pour-over', 'gahwa-service'] },
      { slug: 'tea', name: { ar: 'الشاي', en: 'Tea' }, items: ['karak-chai', 'mint-tea'] },
      { slug: 'coolers', name: { ar: 'المبرّدات', en: 'Coolers' }, items: ['hibiscus-cooler', 'tamarind-lime', 'sobia', 'date-laban-shake', 'taif-rose-lemonade', 'pomegranate-juice'] },
    ],
  },
  {
    slug: 'small-shade',
    kind: 'kids',
    name: { ar: 'ظلٌّ صغير', en: 'Small shade' },
    hour: { ar: 'للصغار', en: 'For children' },
    description: { ar: 'أطباقٌ صغيرة للضيوف الصغار، من المطبخ نفسه والنار نفسها.', en: 'Small plates for small guests, from the same kitchen and the same fire.' },
    schedule: [],
    image: 'craft-server-hands',
    categories: [{ slug: 'little-plates', name: { ar: 'أطباق صغيرة', en: 'Little plates' }, items: ['little-shish', 'manakish-bites', 'kofta-sliders', 'fruit-cup'] }],
  },
];

/** Ramadan menus (visible only while the Ramadan seasonal mode is active). */
export const ramadanMenus: SeedMenu[] = [
  {
    slug: 'iftar',
    kind: 'iftar',
    name: { ar: 'الإفطار', en: 'Iftar' },
    hour: { ar: 'عند المغرب', en: 'At sunset' },
    description: {
      ar: 'يبدأ حين تغيب الشمس عن الفناء: تمرٌ ولبن، ثم الشوربة، ثم ما طبخه الصبر طوال النهار.',
      en: 'It begins when the sun leaves the courtyard: dates and laban, then soup, then everything patience cooked all day.',
    },
    schedule: [{ weekdays: EVERY_DAY, start: '17:30', end: '21:00' }],
    image: 'place-desert-dusk',
    categories: [
      { slug: 'break-fast', name: { ar: 'فكّ الصيام', en: 'Breaking the fast' }, items: ['dates-laban', 'sobia', 'tamarind-lime', 'hibiscus-cooler'] },
      { slug: 'iftar-table', name: { ar: 'سفرة الإفطار', en: 'The iftar table' }, items: ['sambousek', 'harees-lamb', 'jareesh', 'saleeg', 'lamb-mandi', 'hassawi-kabsa'] },
      { slug: 'iftar-sweets', name: { ar: 'حلو رمضان', en: 'Ramadan sweets' }, items: ['luqaimat', 'kunafa-nabulsi', 'umm-ali'] },
    ],
  },
  {
    slug: 'suhoor',
    kind: 'suhoor',
    name: { ar: 'السحور', en: 'Suhoor' },
    hour: { ar: 'قبل الفجر', en: 'Before dawn' },
    description: {
      ar: 'أطباقٌ تُبقيك حتى الغروب، تُقدَّم في فناءٍ ساهر حتى الثالثة.',
      en: 'Dishes to carry you until sunset, served in a courtyard that stays awake until three.',
    },
    schedule: [{ weekdays: EVERY_DAY, start: '22:00', end: '03:00' }],
    image: 'place-lantern',
    categories: [
      { slug: 'suhoor', name: { ar: 'السحور', en: 'Suhoor' }, items: ['tamees-foul', 'mutabbaq', 'balaleet', 'masoub', 'labneh-zaatar', 'mint-tea', 'karak-chai'] },
    ],
  },
];
