import type { SeedPromotion } from './types';

/**
 * Promotion codes. Percentages are whole numbers; amounts (value for 'fixed', maxDiscount, minOrder) are halalas.
 * The first entry is the everyday code used by demos and tests: active, percentage, every channel, both houses.
 */
export const promotions: SeedPromotion[] = [
  {
    code: 'LONGSHADE',
    description: {
      ar: 'خصم ١٥٪ على الطلبات من ١٠٠ ريال فأكثر، بحدٍّ أقصى ٥٠ ريالاً، في الصالة وفي التوصيل والاستلام.',
      en: '15% off orders of SAR 100 or more, up to SAR 50, at the table, for delivery or for pickup.',
    },
    kind: 'percent',
    value: 15,
    maxDiscount: 5000,
    minOrder: 10000,
    startsInDays: -7,
    endsInDays: 45,
    usageLimit: null,
    perCustomerLimit: 3,
    firstOrderOnly: false,
    branches: null,
    channels: null,
    active: true,
  },
  {
    code: 'FIRSTSHADE',
    description: {
      ar: 'لطلبك الأول بالتوصيل: خصم ٢٠٪، بحدٍّ أقصى ٤٠ ريالاً.',
      en: 'For your first delivery order: 20% off, up to SAR 40.',
    },
    kind: 'percent',
    value: 20,
    maxDiscount: 4000,
    minOrder: 0,
    startsInDays: null,
    endsInDays: null,
    usageLimit: null,
    perCustomerLimit: 1,
    firstOrderOnly: true,
    branches: null,
    channels: ['delivery'],
    active: true,
  },
  {
    code: 'FROMTHEDOOR',
    description: {
      ar: 'استلم طلبك من باب البيت بنفسك، ولك خصم ١٠٪ على الطلبات من ٦٠ ريالاً فأكثر، بحدٍّ أقصى ٣٠ ريالاً.',
      en: 'Collect from the door yourself: 10% off orders of SAR 60 or more, up to SAR 30.',
    },
    kind: 'percent',
    value: 10,
    maxDiscount: 3000,
    minOrder: 6000,
    startsInDays: null,
    endsInDays: null,
    usageLimit: null,
    perCustomerLimit: null,
    firstOrderOnly: false,
    branches: null,
    channels: ['pickup'],
    active: true,
  },
  {
    code: 'SUMMERSHADE',
    description: {
      ar: 'رمز الصيف: خصم ١٠٪ على التوصيل والاستلام. انتهى مع آخر أيام الحرّ.',
      en: 'The summer code: 10% off delivery and pickup. It ended with the heat.',
    },
    kind: 'percent',
    value: 10,
    maxDiscount: 3000,
    minOrder: 5000,
    startsInDays: -60,
    endsInDays: -5,
    usageLimit: null,
    perCustomerLimit: 2,
    firstOrderOnly: false,
    branches: null,
    channels: ['delivery', 'pickup'],
    active: true,
  },
  {
    code: 'PALMGROVE',
    description: {
      ar: 'في بيت وادي حنيفة وحده: ٥٠ ريالاً تُخصم من الطلبات من ٢٥٠ ريالاً فأكثر، لأوّل مئتي طلب.',
      en: 'At the Wadi Hanifah house only: SAR 50 off orders of SAR 250 or more, for the first two hundred orders.',
    },
    kind: 'fixed',
    value: 5000,
    maxDiscount: null,
    minOrder: 25000,
    startsInDays: -3,
    endsInDays: 30,
    usageLimit: 200,
    perCustomerLimit: 1,
    firstOrderOnly: false,
    branches: ['wadi-hanifah'],
    channels: null,
    active: true,
  },
];
