import type { SeedReview } from './types';

/**
 * Guest reviews. Names are fictional. Two thirds Arabic, one third English; 24 published (5 featured),
 * 4 pending, 2 rejected as spam. Responses come from the house, in both languages.
 */
export const reviews: SeedReview[] = [
  // ── Arabic · Al-Balad ───────────────────────────────────────────────────
  {
    name: 'لمى ق.',
    rating: 5,
    title: 'فطورٌ عند السادسة',
    body: 'وصلنا قبل السابعة بقليل، والفناء ما زال بارداً. خرج التميس من التنّور أمامنا، والفول بالكمّون كان كما تصنعه جدّتي تماماً. أجمل ما في المكان أنّ أحداً لا يستعجلك.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 12,
    status: 'published',
    featured: true,
  },
  {
    name: 'عبدالله ب.',
    rating: 5,
    title: 'ظهيرةٌ بلا ظلّ',
    body: 'حضرنا غداء انعدام الظلّ في يوليو. وقفت الشمس فوق الفناء تماماً، واختفى ظلّ الليمونة دقائق، والطاقم يدور علينا بماء الورد البارد. لحظةٌ غريبة وجميلة، صفّق لها الناس دون أن يتّفقوا على ذلك.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 84,
    status: 'published',
    featured: true,
  },
  {
    name: 'ريم ح.',
    rating: 4,
    title: 'ليلة خميسٍ مزدحمة',
    body: 'الأطباق ممتازة، خاصّةً السمك في الملح والمطبّق. أنقصت نجمةً لأنّ انتظارنا طال قرابة نصف ساعةٍ بين الطبقين ليلة الخميس، لكنّ النادل اعتذر بلطف وأحضر لنا لقيماتٍ على حساب البيت.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 20,
    status: 'published',
  },
  {
    name: 'فهد س.',
    rating: 3,
    title: 'جميل، لكنّ السطح كان خانقاً',
    body: 'المكان جميل والأكل نظيف الطعم، لكنّنا جلسنا على السطح في أوّل سبتمبر، والرطوبة كانت ثقيلة، والمراوح لم تكفِ. كان الأولى أن ينبّهونا عند الحجز. الصياديّة ممتازة.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 33,
    status: 'published',
    response: {
      ar: 'معك حقّ يا فهد، وكان علينا أن ننبّهك. صارت رسالة الحجز تذكر أنّ السطح رطبٌ في أواخر الصيف، وتقترح الليوان بدلاً منه. ننتظرك في ليلةٍ أبرد، والقهوة علينا. — ريم بخش',
      en: 'You are right, Fahad, and we should have told you. Our booking message now mentions that the roof is humid in late summer and offers the liwan instead. Come back on a cooler night; the coffee is on us. — Reem Bakhsh',
    },
  },
  {
    name: 'نوف ع.',
    rating: 5,
    title: 'المزولة',
    body: 'قائمة التذوّق مرتّبة كأنّها يومٌ كامل. أعجبني طبق الظهيرة: سمكٌ نيّء بالليمون والفلفل الأخضر، خفيفٌ وحادّ. والخاتمة كأس شاي وتمرة، ولم أتوقّع أن تكون أجمل ما في الليلة.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 47,
    status: 'published',
  },
  {
    name: 'سلطان م.',
    rating: 4,
    title: 'أطفالي أحبّوا المكان',
    body: 'جئنا مع ثلاثة أطفال، وكنت أخشى أن نزعج الناس. أعطوهم أوراقاً وأقلاماً ليرسموا ظلّ الشجرة، وقائمة الصغار جيّدة فعلاً. الكراسي العالية قليلة، فاطلبوها عند الحجز.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 60,
    status: 'published',
  },
  {
    name: 'هيفاء ز.',
    rating: 5,
    title: 'ليموناضة الورد',
    body: 'جلست وحدي في العصر ومعي كتاب، وطلبت ليموناضة ورد الطائف واللقيمات. وصلت اللقيمات حارّة، ورائحة الورد خفيفة لا تطغى. ولم يسألني أحدٌ إن كنت أنتظر أحداً، وهذا لطفٌ نادر.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 9,
    status: 'published',
  },
  {
    name: 'ماجد ر.',
    rating: 5,
    body: 'الخبز. يكفي الخبز. وبعده عريكةٌ بعسل السدر.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 102,
    status: 'published',
  },
  {
    name: 'جود ك.',
    rating: 4,
    title: 'هدوءٌ في قلب البلد',
    body: 'تمشّينا في البلد ثم دخلنا الزقاق، فانقطعت الضوضاء فجأة. الأسعار مرتفعةٌ قليلاً على الغداء، لكنّ الجودة تبرّرها. والجريش أطيب ما أكلت هذا الشهر.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 140,
    status: 'published',
  },
  {
    name: 'أسماء ي.',
    rating: 5,
    title: 'طاولة الشيف',
    body: 'ثمانية مقاعد وأمسيةٌ كاملة. تشرح الشيف لميس كلّ طبقٍ كأنّها تحكي عن أهلها. السعر مرتفع، لكنّي سأعود.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 2,
    status: 'pending',
  },
  {
    name: 'متجر ر.',
    rating: 5,
    title: 'عرضٌ خاص',
    body: 'نقدّم خدمات زيادة المتابعين والتقييمات بأسعارٍ منافسة، ونتائج مضمونة خلال ٢٤ ساعة. راسلونا الآن على الخاص.',
    locale: 'ar',
    branch: 'al-balad',
    daysAgo: 15,
    status: 'rejected',
  },

  // ── Arabic · Wadi Hanifah ───────────────────────────────────────────────
  {
    name: 'راشد ع.',
    rating: 5,
    title: 'مثلّثات الضوء',
    body: 'جلسنا في الفناء عصراً، والضوء يدخل من فتحات الجدار مثلّثاتٍ تتحرّك على الأرض ببطء. القهوة الخولانية من أطيب ما شربت في الرياض، وشرح لنا الباريستا من أيّ مدرّجٍ جاءت.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 18,
    status: 'published',
    featured: true,
  },
  {
    name: 'منيرة ف.',
    rating: 5,
    title: 'جريش أمّي',
    body: 'الجريش هنا من قمح حائل، واللبن طازج، والبصل المحمّص مقرمش. أخذت والدتي معي، فقالت إنّه يذكّرها ببيت أهلها في الخرج. وهذا يكفيني.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 26,
    status: 'published',
  },
  {
    name: 'تركي ش.',
    rating: 3,
    title: 'الطعام ممتاز والخدمة بطيئة',
    body: 'الكبسة الحساوية ممتازة، وريش الغنم استوت كما طلبت. لكنّ الخدمة كانت بطيئة جدّاً ليلة الجمعة، وانتظرنا الحساب عشرين دقيقة. المكان يستحقّ تنظيماً أفضل وقت الزحام.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 39,
    status: 'published',
    response: {
      ar: 'شكراً يا تركي على صراحتك. كان عندنا نقصٌ في الطاقم تلك الليلة، وهذا سببٌ لا عذر. أضفنا مضيفاً في ليالي الخميس والجمعة، وصار بإمكانك أن تدفع من رمز الطاولة دون أن تنتظر أحداً. — راكان الحارثي',
      en: 'Thank you for being straight with us, Turki. We were short-staffed that Friday, which is a reason, not an excuse. We have added a host on Thursday and Friday nights, and you can now pay from the table code without waiting for anyone. — Rakan Al-Harthi',
    },
  },
  {
    name: 'لولوة م.',
    rating: 4,
    title: 'المجلس الخاص',
    body: 'حجزنا المجلس لعشاءٍ عائلي من أربعة عشر شخصاً. الجلسة الأرضية مريحة، والمنحدر كان جاهزاً لجدّتي دون أن نطلبه مرّتين. الحلو كان أقلّ ممّا توقّعنا، والباقي ممتاز.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 54,
    status: 'published',
    response: {
      ar: 'شكراً يا لولوة، وسلامنا لجدّتك. أخذت نورة ملاحظتك عن الحلو بجدّ، فصارت قائمة المجلس تُختم بكعكة التمر بكراميل الطحينة بدلاً من الكنافة. — ريم بخش',
      en: 'Thank you, Lulwa, and our regards to your grandmother. Noura took your note on the sweets to heart: the majlis menu now ends with the date cake and tahini caramel instead of the kunafa. — Reem Bakhsh',
    },
  },
  {
    name: 'خالد ن.',
    rating: 5,
    body: 'أجمل حوشٍ في الرياض. الهواء باردٌ تحت سقف النخل حتى في الظهر.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 71,
    status: 'published',
  },
  {
    name: 'سارة د.',
    rating: 5,
    title: 'ساعة الخولاني',
    body: 'حضرت درس القهوة مع يوسف. تعلّمت أنّ مئتي مترٍ من الارتفاع تغيّر الفنجان فعلاً، وكنت أظنّها مبالغة. عدت إلى البيت بكيس بنٍّ وميزانٍ جديد.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 95,
    status: 'published',
  },
  {
    name: 'عبدالرحمن ط.',
    rating: 4,
    title: 'فطورٌ هادئ',
    body: 'الفطور ممتاز، والمطبّق أطيب ما جرّبنا. أتمنّى لو كان الليوان أبرد في ظهيرة الصيف، فالمراوح وحدها لا تكفي حين تشتدّ الشمس.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 122,
    status: 'published',
  },
  {
    name: 'بدر هـ.',
    rating: 5,
    title: 'طاولة الشيف مع راكان',
    body: 'ثمانية مقاعد حول الجمر، وكلّ طبقٍ يأتي به الشيف بنفسه. سألته عن خلطة البهارات فابتسم ولم يجب.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 110,
    status: 'published',
  },
  {
    name: 'دانة س.',
    rating: 4,
    body: 'أحببنا المكان، والمندي ممتاز. العزف على العود في العصر جميل، لكنّه انتهى أبكر ممّا أردنا.',
    locale: 'ar',
    branch: 'wadi-hanifah',
    daysAgo: 1,
    status: 'pending',
  },

  // ── English · Al-Balad ──────────────────────────────────────────────────
  {
    name: 'Hannah W.',
    rating: 5,
    title: 'Breakfast at seven',
    body: 'We came for breakfast on our first morning in Jeddah and came back three times in five days. The tamees arrives too hot to hold. I am still trying to recreate the shakshuka with dried lime at home. The staff were very patient with our terrible Arabic.',
    locale: 'en',
    branch: 'al-balad',
    daysAgo: 28,
    status: 'published',
    featured: true,
  },
  {
    name: 'James O.',
    rating: 4,
    title: 'Lovely courtyard, loud by eleven',
    body: 'Beautiful house and very good food; the salt-baked fish was the highlight. One star off because by eleven on a Thursday the courtyard was loud enough that we struggled to hear each other. Go early, or ask for the liwan.',
    locale: 'en',
    branch: 'al-balad',
    daysAgo: 44,
    status: 'published',
  },
  {
    name: 'Priya N.',
    rating: 3,
    title: 'Great food, muddled booking',
    body: 'The food was excellent, particularly the mutabbaq and the kunafa. But the deposit for our table of six was not made clear until the last step, and the confirmation email arrived in Arabic only, although I had booked in English. Small things, but they add up.',
    locale: 'en',
    branch: 'al-balad',
    daysAgo: 76,
    status: 'published',
    response: {
      ar: 'شكراً يا بريا. كان ينبغي أن يظهر العربون من الخطوة الأولى، وقد صار يظهر الآن. أمّا رسالة التأكيد فكانت خللاً من جهتنا أصلحناه، فهي تصلك الآن باللغة التي حجزت بها. — ريم بخش',
      en: 'Thank you, Priya. The deposit should have been clear from the first step, and now it is. The Arabic-only confirmation was a fault on our side, since fixed: emails now arrive in the language you booked in. — Reem Bakhsh',
    },
  },
  {
    name: 'Tom H.',
    rating: 5,
    title: 'The Sundial',
    body: 'Seven courses that genuinely follow the day, from dates and cream to a single glass of mint tea. The raw fish at noon was the best thing I ate on the whole trip. No alcohol, and I did not miss it once.',
    locale: 'en',
    branch: 'al-balad',
    daysAgo: 131,
    status: 'published',
    featured: true,
  },
  {
    name: 'Claire B.',
    rating: 4,
    title: 'Worth the alarm clock',
    body: 'The dawn bread class starts early but is worth it. Abu Saleh speaks very little English and did not need to. Bring a hair tie; the tannour is hot.',
    locale: 'en',
    branch: 'al-balad',
    daysAgo: 3,
    status: 'pending',
  },

  // ── English · Wadi Hanifah ──────────────────────────────────────────────
  {
    name: 'Daniel K.',
    rating: 5,
    title: 'The calmest lunch in Riyadh',
    body: 'Escaped a long day of meetings for lunch here. Mud walls, a palm-trunk ceiling and air that is somehow ten degrees cooler than the car park. The red rice kabsa is generous enough for two.',
    locale: 'en',
    branch: 'wadi-hanifah',
    daysAgo: 22,
    status: 'published',
  },
  {
    name: 'Aisha R.',
    rating: 4,
    title: 'Coffee worth the drive',
    body: 'The Khawlani pour-over is the reason to come. The barista asked how I like my coffee before suggesting anything. The sweets were good, though the date cake was a little dry on our visit.',
    locale: 'en',
    branch: 'wadi-hanifah',
    daysAgo: 65,
    status: 'published',
    response: {
      ar: 'شكراً يا عائشة. كانت كعكة التمر يومها من خَبزة الصباح، وصرنا نخبزها مرّتين في اليوم في بيت الوادي. — نورة حمدان',
      en: 'Thank you, Aisha. The date cake that day was from the morning bake; we now bake it twice a day at the Wadi Hanifah house. — Noura Hamdan',
    },
  },
  {
    name: 'Mark S.',
    rating: 3,
    title: 'Beautiful room, uneven evening',
    body: 'The majlis is a beautiful room and the lamb was superb. But two of our courses arrived lukewarm, and we had to ask twice for more water. At this price I expected the evening to run more smoothly.',
    locale: 'en',
    branch: 'wadi-hanifah',
    daysAgo: 98,
    status: 'published',
    response: {
      ar: 'شكراً يا مارك، ونأسف للطبقين؛ لم يكن ذلك المستوى الذي نريده للمجلس. صار للمجلس الآن نادلٌ مخصّص طوال الأمسية، ويسعدنا أن نستقبلكم مرّةً أخرى ضيوفاً علينا. — راكان الحارثي',
      en: 'Thank you, Mark, and we are sorry about those two courses. That is not the standard we want for the majlis. It now has its own server for the whole evening, and we would like to welcome you back as our guests. — Rakan Al-Harthi',
    },
  },
  {
    name: 'Leila F.',
    rating: 5,
    title: 'An hour longer than planned',
    body: 'Came with my parents for the long shade. The oud, the triangles of light on the floor, the kleija. My father stayed an hour longer than he meant to.',
    locale: 'en',
    branch: 'wadi-hanifah',
    daysAgo: 2,
    status: 'pending',
  },
  {
    name: 'Promo T.',
    rating: 5,
    title: 'Amazing offer',
    body: 'Nice restaurant. We sell five-star reviews and followers for any business, cheapest prices and fast delivery. Contact our team today.',
    locale: 'en',
    branch: 'wadi-hanifah',
    daysAgo: 7,
    status: 'rejected',
  },
];
